- app/helpers/templates_helper.rb
- app/models/campaign_pages_widget.rb
- app/views/campaign_pages/_form.slim
- app/views/widgets/thermometer/_display.slim
- app/views/widgets/thermometer/_form.slim
Adding a pull request for the cherry-picked thermometer widget commits separate from the campaign-pages-to-campaigns branch. Note that on that branch, there are some changes to how the widget forms or displays are constructed, including changes to the thermometer widget. This is a slightly older version of the widget, consistent with the development branch, because there are some changes to the widgets on campaign-pages-to-campaigns that haven't made it to development yet (and so the updated thermometer form wouldn't work on development).
> Thermometer

- README.md
The instructions for setting up the development environment were out of date. This adds some missing steps and fixes some typos.
> update Readme instructions after setting up dev env

- db/seeds.rb
`{tag_name: '+Test', actionkit_uri: '/rest/v1/tag/947/'}` has the same URI as https://github.com/SumOfUs/Champaign/blob/master/db/seeds.rb#L126
If the `+` tags are required, I'll just change the URI tag ID to something unique.
> Removes '+' tags (one has a duplicate actionkit_uri)

- app/services/search/page_searcher.rb
- app/services/search/widget_searcher.rb
- app/views/campaign_pages/index.slim
- spec/service_objects/search_spec.rb
- spec/support/factories.rb
Functionality to search by widget type works fine in development. Specs fail, though, assumingly due to the fact that i'm passing params wrong and when I call page_searcher.search with the params, the switch just goes through because it fails to match the cases with the search parameters.
> Search by widget type

- app/assets/stylesheets/common.scss
- app/controllers/campaign_pages_controller.rb
- app/controllers/plugins/thermometers_controller.rb
- app/models/plugins/thermometer.rb
- app/views/campaign_pages/edit.slim
- app/views/campaign_pages/index.slim
- app/views/layouts/application.slim
- app/views/plugins/thermometers/_form.slim
- app/views/shared/_error_messages.slim
- app/views/shared/_success_message.slim
- config/locales/en.yml
- db/migrate/20150812172556_remove_language_id_null_constraint.rb
- db/schema.rb
does
- show validation errors on campaign page and thermometer plugin
- show success messages for campaign page and thermometer plugin
- adds a dropdown to pick the template for the page
- adds some view links to make clicking around easier
does not 
- show validation errors / success on action plugin
> Validation messages, template picker

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/campaign_page.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/campaign_pages.scss
- app/controllers/plugins/actions_controller.rb
- app/controllers/plugins/thermometers_controller.rb
- app/controllers/plugins_controller.rb
- app/helpers/campaign_pages_helper.rb
- app/models/plugins.rb
- app/views/campaign_pages/_header.html.slim
- app/views/campaign_pages/edit.slim
- app/views/layouts/application.slim
- app/views/plugins/actions/_form.slim
- app/views/plugins/shared/_toggle_form.html.slim
- app/views/plugins/show.html.slim
- app/views/plugins/templates/main.liquid
- app/views/plugins/thermometers/_form.slim
- config/application.rb
- config/routes.rb
- lib/tasks/champaign.rake
- spec/controllers/plugins_controller_spec.rb
- spec/helpers/campaign_pages_helper_spec.rb
- spec/lib/champaign_queue/clients/sqs_spec.rb
Mainly DRYing up view code (using partials and helpers), but also returns the original toggle feature allowing campaigners to switch plugins on and off.
With toggling no changes are required on the template side, so you could have a template that handles all possible plugins, but gracefully deals with those that are switched off. I imagine we'll have a master template like this. For more custom templates @NealJMD's solution would then kick in.
Also, I've moved plugin settings from the main campaign page edit view. As plugin options grew, this page would have become a campaigner's nightmare. Now plugins exist in their own tab.
NOTE: This PR requires two rake tasks to be run:
`rake champaign:activate_plugins`
`rake champaign:seed_liquid`
> Toggle feature and refactoring

- Dockerfile
- Gemfile
- Gemfile.lock
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.slim
- config/newrelic.yml
- config/routes.rb
- docker-compose.yml
This removes the ability to sign up with a username and password from our site.
There’s one catch I’m seeing, which is that the password login page still has a sign up link on it (which will now return a 404) - I’m not sure where that page is designed/modified, so I’m not sure how to remove that link.
> Devise disable signup

- app/views/share/index.html.slim
This is intended to make these buttons stand out a bit. I expect we’ll want a thematic unity to our buttons at some point (having all edit buttons be X color kind of thing), but I don’t think we have to make that decision for this yet.
> Modifying colors of buttons on Share Variation creation page

- lib/liquid_markup_seeder.rb
after the last update, the liquid seeder was updating existing liquid partials / templates, but not actually saving the changes to the db. this fixes that bug.
> fix liquid seeder

- .ebextensions/03_container_commands.config
- circle.yml
This changes the container our rake tasks are issued at deploy time. Staging app is the container AWS spins up to set up your new application, so it contains the files from our application. Running the rake tasks there will perform migrations that are up-to-date with the migration requirements of our new deploy, and upload static assets that'll match the fingerprints on the requests for them.
> Aws deploy

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/sumofus/global/typography.scss
- app/controllers/pages_controller.rb
- app/controllers/plugins/actions_controller.rb
- app/liquid/liquid_helper.rb
- app/liquid/liquid_renderer.rb
- app/models/plugins/action.rb
- app/views/plugins/actions/_action.liquid
- app/views/plugins/actions/_form.slim
- app/views/plugins/actions/_preview.html.slim
- db/migrate/20151002221626_add_cta_to_plugins_actions.rb
- db/schema.rb
- spec/controllers/pages_controller_spec.rb
- spec/factories/plugins_actions.rb
- spec/models/plugins/action_spec.rb
Three changes
- allow the CTA button on the action form to be set in the admin. On new forms, it defaults to "Sign the Petition" but on old ones it may need to go back and be changed again.
- the country dropdown now has the user's country automatically selected based on their request location.
- reset.css clobbered bold tags, added them to the list of strong
> CTA customization and country auto-fill

- app/controllers/share/shares_controller.rb
- app/models/share/email.rb
- app/models/share/facebook.rb
- app/models/share/twitter.rb
- app/models/share/variant.rb
- app/services/share_progress_variant_builder.rb
- spec/controllers/share/shared_examples.rb
- spec/services/share_progress_variant_builder_spec.rb
Up to this point, our share button creation assumed that if it passed our validation, it also passed the validation on ShareProgress. This changes that to take any errors returned by SP seriously. It also tries to be tolerant of the SP API sending back stuff completely different from what they currently send, cause you never know.
> Share progress validation

- app/views/share/facebooks/_facebook.html.slim
- app/views/share/facebooks/_share_fields.html.slim
- config/locales/en.yml
Don't show broken image when missing. Allow campaigner to upload a new image for existing fb share.
> Upload new image for existing fb share

- app/assets/stylesheets/sumofus/global/typography.scss
- app/liquid/views/layouts/sumofus.liquid
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
This takes care of three little tickets
- make italics in the WYSIWYG actually show up as italic on the campaign page
- link only the SOU logo to SOU.org, not the entire header
- make the log in page feature Google Oauth much more prominently.
> Little fixes

- circle.yml
There's now a testing environment up on Elastic Beanstalk - this change to circle.yml will allow you to specify any branch to deploy to the testing environment. As an type of testing environment that members won't be interacting with, the test env uses the same SQS queue as staging. Consequently, both are handled by the same AK worker. The test env has its own RDS, though, because the desired test branch might have migrations we don't want to hit staging.
> Add option to deploy to testing environment through CircleCI

- app/assets/javascripts/sumofus/backbone/fundraiser_bar.js
- app/assets/stylesheets/sumofus/components/fundraiser.scss
- app/assets/stylesheets/sumofus/components/petition.scss
- app/controllers/pages_controller.rb
- app/liquid/liquid_renderer.rb
- app/liquid/views/partials/_form.liquid
- app/models/plugins.rb
- app/models/plugins/action.rb
- app/models/plugins/fundraiser.rb
- app/models/plugins/has_form.rb
- app/models/plugins/thermometer.rb
- app/services/form_validator.rb
- app/views/form_elements/_element.slim
- app/views/forms/_add_element.slim
- app/views/forms/_preview.html.slim
- app/views/plugins/actions/_action.liquid
- app/views/plugins/fundraisers/_fundraiser.liquid
- spec/controllers/pages_controller_spec.rb
- spec/factories/forms.rb
- spec/javascripts/fixtures/magic_lamp.rb
- spec/javascripts/member-ui/fundraiser_spec.js
- spec/liquid/liquid_renderer_spec.rb
- spec/models/plugins/action_spec.rb
- spec/models/plugins/fundraiser_spec.rb
- spec/models/plugins/plugins_spec.rb
- spec/models/plugins/shared_examples.rb
- spec/models/plugins/thermometer_spec.rb
- spec/services/form_validator_spec.rb
This PR makes the fundraiser bar hide the second step if the member is recognized by akid or member id, and skips the first step, preselecting the amount, if the amount is passed in the url parameters. Most of the code is test code for the javascript and the back end changes made to accomodate this.
The biggest back end change this makes is that we now pass data from the controller to the liquid_data method of the plugins. This allows us to check the form against the existing data to determine if the user data step can in fact be skipped, and tells us if any prefilled data won't pass validation.
> Step skipping

- app/assets/javascripts/sumofus/backbone/fundraiser_bar.js
- app/assets/stylesheets/sumofus/components/fundraiser.scss
- app/assets/stylesheets/sumofus/global/colors.scss
- app/views/plugins/fundraisers/_fundraiser.liquid
- lib/payment_processor/clients/braintree/error_processing.rb
- spec/javascripts/member-ui/fundraiser_spec.js
- spec/requests/api/braintree_spec.rb
This PR shows the donor any errors from the Champaign server. It has built in error messages for card declines and 500 errors, and others simply display the message from Braintree. It includes specs, wrapping up the long-pending specs.
> Donation errors

- app/services/action_builder.rb
- db/seeds.rb
- spec/services/action_builder_spec.rb
There was a bug where we weren't saving any member data aside from the email. It stemmed from a bad assumption of hash keys with a hash with indifferent access. This PR mostly just writes tests around the bug. Should be ready to merge!
It also makes postal code not required by default in seeded form per Eoin's request.
> Remember member

- app/assets/javascripts/ajax.js
- app/assets/javascripts/application.js
- app/assets/javascripts/page_edit_bar.js
- app/assets/javascripts/show_errors.js
- app/assets/javascripts/sumofus/backbone/form_methods.js
- app/assets/javascripts/sumofus/backbone/petition_bar.js
- app/assets/stylesheets/sumofus/components/form.scss
- config/locales/champaign.en.yml
- spec/factories/forms.rb
- spec/javascripts/fixtures/magic_lamp.rb
- spec/javascripts/member-ui/form_error_spec.js
- spec/javascripts/member-ui/fundraiser_spec.js
This PR does a light refactor of `show_errors.js`. Previously, it had this weird global namespace thing, it had a weird design pattern, and it had no spec. Now, it's encapsulated in an object, uses es6, gets imported through browserify, and has a pretty solid spec that tests it through the integration with the petition bar.
There's a small outstanding bug where the border hasn't been changing on the country selector when there's an error and I want to wrap that up before this gets merged, but the code is ready for review.
> Refactor error display

- app/liquid/liquid_file_system.rb
- config/settings/production.yml
- spec/requests/liquid_rendering.rb
When we upgraded to ruby 2.3.0, it fixed [the ruby bug](https://bugs.ruby-lang.org/issues/10700) where filenames on case-sensitive OSes were read case-insensitively. This revealed a bug with the `LiquidFileSystem` class, and the fact that we needed smoke tests on rendering the sidebars. This fixes those things.
> Fix partial reading

- app/assets/javascripts/sumofus.js
- app/assets/javascripts/sumofus/backbone/campaigner_overlay.js
- app/assets/stylesheets/sumofus/components/campaigner-overlay.scss
- app/views/layouts/sumofus.slim
- app/views/pages/_campaigner_overlay.slim
- app/views/pages/show.slim
- config/locales/sumofus.fr.yml
This PR adds a little tab to the bottom left corner of all action pages to alert campaigners as to whether it is published or not. This includes a link to publish or unpublish directly there, a link to edit the page, and a n X in the corner to dismiss it in case it's covering something you want to see.
I also threw the two missing french translations into this PR.
> Publishing notice

- app/liquid/views/partials/_links.liquid
- app/models/link.rb
- app/views/pages/_link.slim
- spec/models/link_spec.rb
Before, when a campaigner created a link to a source for a page, if that was entered without a protocol like `http://` as a prefix, rails assumed it was an internal link and tried to link you to `localhost:3000/pages/motherjones.org`. This validates that all links are saved with a protocol, and has a filter run before validation to add the protocol deferring prefix `//` to urls that have none.
It also changes the links on the pages to open in new tabs instead of the existing one.
> Remote links

- Gemfile
- Gemfile.lock
- circle/specs-and-rake-tasks
Addresses two issues
- someone merged a [commit](https://github.com/SumOfUs/Champaign/commit/02bd77e13e9b48c404f7a9808be874018f4f9a56) that turned off the js tests cause we were in a hurry to deploy to staging, but then forgot to turn them back on when the hastily constructed demo branch was turned into the new base branch. This PR turns those tests back on.
- the JS tests stopped being able to run locally when the rails and ruby version bumps brought us onto `sprockets-rails` 3. There is a [known issue](https://github.com/modeset/teaspoon/issues/443) where sprockets 3 breaks teaspoon. The current recommended solution is to stay on `sprockets-rails` 2.3, so I did that. 
JS tests are now passing on CI!
> Fix JS tests

- app/controllers/api/actions_controller.rb
- app/controllers/api/braintree_controller.rb
- app/models/member.rb
- app/services/action_builder.rb
- app/services/name_splitter.rb
- spec/models/member_spec.rb
- spec/services/name_splitter_spec.rb
This is a hack. I’m not going to paper it over - it’s not a complete way to handle the fact that our forms ask for full name but our model assumes first/last name. This code is only here to solve that very specific problem, because other issues are being held up by that issue.
So. This is not good code, in the sense that it’s not doing nice things. But it’s code! It works! It has tests! It doesn’t fix the fact that the name field shows up on a form even when your name is present, but I wanted to get it out into the wild before I worried about that.
> Hack to make full_name and first/last name play together nicely.

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/liquid/liquid_renderer.rb
- spec/controllers/pages_controller_spec.rb
- spec/liquid/liquid_renderer_spec.rb
- spec/requests/localization_spec.rb
I18n doesn't work on a per-request basis on a multi-threaded server, so what I'm doing is forcing it to
check what localization should be use on a per-request basis. This gets called on all requests, and the
case goes through different controllers, checks whether it could be a controller where internalization
would be required (for api/actions and pages), and then sets the locality if appropriate.
This has broken form validation right now - I'm not exactly sure why that would be, but I get a 500 for the jquery request. @NealJMD perhaps you have an idea as to why that would happen. I also don't think this has to stay as-is - I'm just sharing ideas. This fixes the problem and breaks a bunch of specs. If you're OK with the outline of how this might work and would like to implement this your …
> Fixes bug with sticky localization - sets locale on a request-per-request basis

- config/settings/production.yml
I suspect that donations aren't going through on prod cause we didn't give merchant accounts. 
This also fixes braintree on staging, which broke when we tried to use the sandbox keys but claimed our environment was production.
> add merchant account names to prod settings, move bt env to ENV

- app/assets/javascripts/application.js
- app/assets/javascripts/layout_picker.js
- app/assets/javascripts/selectize_config.js
- app/assets/javascripts/sumofus/backbone/fundraiser_bar.js
- app/assets/javascripts/sumofus/backbone/petition_bar.js
- app/assets/stylesheets/page-edit.scss
- app/assets/stylesheets/sumofus/components/petition.scss
- app/controllers/api/actions_controller.rb
- app/controllers/pages_controller.rb
- app/liquid/liquid_renderer.rb
- app/liquid/views/layouts/post-action-share.liquid
- app/liquid/views/layouts/post-donation-share.liquid
- app/models/page.rb
- app/services/page_follower.rb
- app/views/pages/_collapsing_layout_select.slim
- app/views/pages/_layout_select.slim
- app/views/pages/_settings_form.slim
- app/views/plugins/petitions/_petition.liquid
- config/locales/champaign.en.yml
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
- db/migrate/20160125205126_rename_secondary_liquid_layout.rb
- db/migrate/20160125211650_add_follow_up_plan.rb
- db/schema.rb
- spec/controllers/api/actions_controller_spec.rb
- spec/controllers/pages_controller_spec.rb
- spec/liquid/liquid_renderer_spec.rb
- spec/models/page_spec.rb
- spec/services/page_follower_spec.rb
This PR completes @paulaferris's long requested feature to be able to daisy-chain pages together. it allows a campaigner to pick the name of a page that it should redirect to after the action is completed.
It also has a fix for a UI bug where the petition stickiness would jump and german "Sign the petition" would wrap in an awkward way.
> Daisy chain

- app/controllers/api/actions_controller.rb
I had set it to an hour at the beginning, so it expired much too fast.
> Make member_id cookie last two years

- app/views/layouts/sumofus.slim
- circle.yml
Tiny PR. I had hoped to move our sumofus js asset file also, but the json object we print half way down the body is dependent on `jquery` and `PetitionBar` (it's a bigger job for another day).
> [PRE DEPLOY] Move some assets to bottom of page

- app/controllers/api/braintree_controller.rb
- app/models/payment.rb
- app/models/payment/braintree_subscription.rb
- config/routes.rb
- db/migrate/20160219174402_add_action_id_to_subscription.rb
- db/schema.rb
- lib/payment_processor/clients/braintree/subscription.rb
- lib/payment_processor/clients/braintree/webhook_handler.rb
- spec/controllers/api/braintree_controller_spec.rb
- spec/lib/payment_processor/clients/braintree/subscription_spec.rb
- spec/lib/payment_processor/clients/braintree/webhook_handler_spec.rb
- spec/models/payment/braintree_subscription_spec.rb
- spec/models/payment_spec.rb
- spec/requests/api/braintree_spec.rb
- spec/requests/api/braintree_webhook_spec.rb
This PR refactors the webhook method into a service class. It also simplifies the logic quite a bit by looking up the original Action by subscription_id, then just pushing that same Action directly to the queue. It will have unit tests on the controller and class, and it has an integration spec.
> [Pre-release] Webhook

- app/services/page_follower.rb
- app/views/pages/_sidebar.slim
- app/views/pages/edit.slim
- app/views/pages/index.slim
- config/routes.rb
- spec/liquid/liquid_renderer_spec.rb
- spec/routing/pages_routing_spec.rb
- spec/services/page_follower_spec.rb
@edubsky suggested it would be better to use `/a/my-slug` instead of `/pages/my-slug` for member-facing pages, and it seemed like it was worth getting out before launch so we wouldn't have to deal with changing links after we sent them out.
> Page short links

- app/views/plugins/fundraisers/_fundraiser.liquid
There was a bug where going through the Paypal flow hid the recurring donation checkbox, so we couldn't upsell people. 
Before:
After:
> Don't hide monthly subscription box when hiding credit card fields

- app/services/action_queue.rb
- spec/requests/api/braintree_spec.rb
- spec/requests/api/braintree_webhook_spec.rb
- spec/services/action_builder_spec.rb
We weren't passing the akid through on donations, so the mailing ID was missing and our tracking in AK was messed up. This is a one-line fix.
> Pass akid through to donations

- app/liquid/liquid_tag_finder.rb
- app/liquid/views/layouts/fundraiser-with-large-image.liquid
- app/liquid/views/layouts/fundraiser-with-small-image.liquid
- app/liquid/views/layouts/petition-with-large-image.liquid
- app/liquid/views/layouts/petition-with-small-image.liquid
- app/liquid/views/layouts/post-donation-share.liquid
- app/liquid/views/layouts/post-petition-share.liquid
- lib/liquid_markup_seeder.rb
- spec/lib/liquid_markup_seeder_spec.rb
- spec/liquid/liquid_tag_finder_spec.rb
Right now, there's a one-off rake task that identifies which layouts are primary and which post-action. This leverages the code I wrote for the `experimental` tag to let us set these values in the liquid in our repo, so our templates in the db will stay in sync with our version control by default.
> Make liquid seeder auto-interpret post-action and primary layouts

- app/assets/javascripts/shares_editor.js
- app/views/pages/edit.slim
- fixes a bug where the shares editor would blow up when autosave was on
- changes the order of the plugins on the pages editor, so that petition and fundraiser are moved up and thermometer is moved down
> Campaigner tweaks

- app/liquid/views/partials/_share_page.liquid
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
Previously, our share buttons were all in English, and this fixes that. I'm waiting on Languages team for final translations, but this is ready for code-review / sign-off.
> Translate share buttons

- app/models/plugins.rb
- app/models/plugins/fundraiser.rb
- app/models/plugins/petition.rb
- app/views/plugins/petitions/_petition.liquid
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
- spec/models/plugins/plugins_spec.rb
This PR does two things -
- rather than having default values specified as english strings, we specify them as localization keys and run them through the translation engine with the page's language, falling back to English. This way a German page will default to have German titles and CTAs
- show the petition's `cta` value not just on the button, but also on the petition title. See below
> Mutable petition header and i13ed plugin defaults

- app/assets/stylesheets/sumofus/components/fundraiser.scss
- app/assets/stylesheets/sumofus/components/petition.scss
- app/views/plugins/fundraisers/_fundraiser.liquid
- app/views/plugins/petitions/_petition.liquid
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
This PR adds a disclaimer with a link to our privacy policy to the bottom of petition forms and to the second step of the fundraiser form. It also moves the donation fine print to step 3 of the donation form so it is shown even if the amount is preselected.
Paul originally wanted the donation form's privacy notice to go on step 3, but that made step 3 vertically too long. I also realized that people never skip step 2 if they're registering for the list for the first time, so it makes sense to put it there. Here's how it looks now:
> Add a privacy notice to the bottom of forms with email

- app/controllers/images_controller.rb
- spec/controllers/images_controller_spec.rb
The image controller couldn't handle Image model validation errors and it just returned the error page html and stuffed it in a stupidly long tooltip. This is now handled properly, and I added a spec.
> Make image uploader show model validation errors

- app/assets/stylesheets/sumofus/pages/page.scss
- app/liquid/views/partials/_no_script.liquid
- app/views/plugins/fundraisers/_fundraiser.liquid
- app/views/plugins/petitions/_petition.liquid
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
If you submit our petition or donation forms with javascript turned off, rails authenticity token is not submitted and you get redirected to a 422 page. We might be able to debug around this, but it's a tiny use case, and donations with BT's hosted fields will never work without javascript. Instead, I'm just showing a message to the user about their javascript. I'm waiting on the languages team for translations.
> Show an explanatory message to users with javascript turned off

- app/assets/javascripts/sumofus/backbone/form_methods.js
- app/assets/javascripts/sumofus/backbone/hosted_fields.js
- app/assets/stylesheets/sumofus/components/fundraiser.scss
- app/assets/stylesheets/sumofus/components/petition.scss
- app/assets/stylesheets/sumofus/global/interactive.scss
- app/liquid/views/partials/_form.liquid
- app/models/plugins/thermometer.rb
- app/views/plugins/fundraisers/_fundraiser.liquid
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
- spec/javascripts/member-ui/fundraiser_spec.js
- spec/javascripts/member-ui/petition_spec.js
- spec/models/plugins/thermometer_spec.rb
This takes care of 3 little tickets -
- Paul wants the check boxes to always display on forms, even if we have everything else need from that user. This does that. However, it has no effect on the donation flow - if step 2 would be skipped and it has checkboxes, it 
- Eoin thought the "Welcome back, Eoin!" was cheesy, so I changed it to a little box with their name
- for numbers over 1 million, the thermometer goal readout displayed "1000K" which is not very readable. Now it puts out millions (with one decimal point) if the goal is at least one million.
You can see all these changes in this one screenshot
> Petition tweaks

- app/assets/javascripts/application.js
- app/assets/javascripts/page_edit_bar.js
- app/assets/stylesheets/page-edit.scss
- config/locales/champaign.en.yml
This PR displays a notice in the save box when autosave is turned off and a campaigner has made changes that have not been pushed to the server. It does not display when autosave is turned on because it polls at the same rate as the autosave - if the "Unsaved changes" message would display on autosave, the save has already been dispatched.
> Unsaved notice

- circle.yml
- deploy.sh
This sets up deploy events for New Relic, guarantees that the deploy events get triggered only after the application status is ready and when it's running the application version specified on deploy. It also changes the deploy script in that it now forces the build to wait for the application to be ready before it tries to deploy - this way, builds won't fail because of two deploys happening in a short succession.
> Set up Newrelic deploy event and brush up the deploy script.

- app/assets/javascripts/sumofus/backbone/fundraiser_bar.js
- app/assets/javascripts/sumofus/backbone/hosted_fields.js
- app/models/plugins/fundraiser.rb
- app/views/plugins/fundraisers/_form.slim
- app/views/plugins/fundraisers/_fundraiser.liquid
- config/locales/champaign.en.yml
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
- db/migrate/20160308201945_add_recurring_to_fundraiser.rb
- db/schema.rb
- public/404.html
- spec/javascripts/member-ui/fundraiser_spec.js
- spec/models/plugins/fundraiser_spec.rb
This PR allows a campaigner to select a fundraiser as "Default to one-time donation", "Default to recurring donation", or "Only allow recurring donations" in the back end. That sets the default behavior for whether the fundraiser should have the "make recurring" box checked or not and whether the box should be visible or not. If the url param `recurring_default=recurring`, `recurring_default=only_recurring` or `recurring_default=donation` is passed, that will override the behavior specified in the back-end.
It also shows on the button if this is a recurring donation. I'm still waiting on sign-off from the languages team about the German and French versions, but the English version is below.
> Recurring features

- app/assets/stylesheets/sumofus/components/petition.scss
- app/assets/stylesheets/sumofus/pages/page.scss
- app/models/form.rb
- app/models/plugins/has_form.rb
- app/services/default_form_builder.rb
- circle.yml
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
- db/seeds.rb
- lib/tasks/sumofus.rake
- spec/lib/user_language_iso_spec.rb
- spec/models/plugins/shared_examples.rb
- spec/services/default_form_builder_spec.rb
- spec/services/search/page_searcher/page_searcher_spec_data.rb
This PR wraps up the work to import legacy pages from ActionSweet. It handles a couple of parts that we didn't get to in the first round
- after taking an action on any of these pages, you now get redirected to a generic post-action donate page in the appropriate language
- the generic post-action donate page needed a default form in the right language, so I went ahead and I15d the default forms
- there was a bug where we were keying off of title, not slug, so various pages were all written to the same record, resulting in 404ing a dozen or so slugs.
- I did a bit of work to try to straighten out newline formatting and spacing on the page
> Legacy pages

- Gemfile
- Gemfile.lock
- app/liquid/liquid_i18n.rb
- app/liquid/views/partials/_links.liquid
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
- spec/liquid/liquid_i18n_spec.rb
OK -- Saturday morning fun. Attempting i18n of the date (in particular, month) based on some reading on liquid, for a ticket @edubsky created.
Questions: 
1) @edubsky: I think the traditional format in DE is 28. Mai 2015. This writes format as 28 Mai 2015 (i.e. without the period after the day) to keep it simple and standard across EN/DE/FR. Is that format OK or does it look odd/wrong in DE?
2) Do I also need to manually update the liquid templates on staging and production via the campaigner UI, or does this propagate from the codebase? 
3) Tell me what I've got wrong or missed! Haven't been able to test locally or anything as don't have Champaign running locally, and of course I'm totally winging it here.
> I18n link dates

- app/controllers/pages_controller.rb
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
- lib/tasks/sumofus.rake
- spec/controllers/pages_controller_spec.rb
This PR wraps up the last two things for the legacy pages:
- it adds the `Actionsweet_Legacy` tag to all the legacy pages
- it redirects 404s on `pages#show` to sumofus.org rather than showing the 404 page.
> Legacy tag

- app/assets/javascripts/configure_wysiwyg.js
Pretty self explanatory. I declined to make it do the HTML pretty-formatting cause it only did that in the code view, so you got the unsaved changes flag every time you flicked back and forth between code and WYSIWYG.
> make code lines wrap on WYSIWYG

- app/views/layouts/sumofus.slim
- app/views/pages/show.slim
Paul wants us to explicitly list the language code on member facing pages to allow Optimizely to hook into them. Per [the W3 spec](https://www.w3.org/TR/html5/semantics.html#the-html-element), the right place to do that is on the `lang` attribute of the page's HTML tag. This is also used by screenreaders to flag what accent to use. 
I also removed a duplicate key cause it was giving me warnings when running rspec.
> Add lang property to <html> tag on member facing pages

- app/models/payment/go_cardless.rb
- app/models/payment/go_cardless/customer.rb
- app/models/payment/go_cardless/payment_method.rb
- app/models/payment/go_cardless/subscription.rb
- app/models/payment/go_cardless/transaction.rb
- db/migrate/20160404203052_create_go_cardless_tables.rb
- db/schema.rb
- spec/factories/payment_go_cardless_customers.rb
- spec/factories/payment_go_cardless_payment_methods.rb
- spec/factories/payment_go_cardless_subscriptions.rb
- spec/factories/payment_go_cardless_transactions.rb
- spec/models/payment/go_cardless/customer_spec.rb
- spec/models/payment/go_cardless/payment_method_spec.rb
- spec/models/payment/go_cardless/subscription_spec.rb
- spec/models/payment/go_cardless/transaction_spec.rb
Today I added the tables, models, and model specs for the GoCardless integration.The target branch for this PR is just the `going-cardless` branch, which is very much WIP itself, so this PR is just a chance to comment and make sure we're aligned about this.
One of my goals was to try to prevent doing excessive bookkeeping by writing anything in two places or tracking fields we will probably never use and that we could just query GC for if we want them.
A couple decisions I made -
- all the tables are related, using the ids of the rows in our own tables as foreign keys (not GC ids).
- all relations between new tables are indexed
- every table stores its GC id in a field called `go_cardless_id`
- we don't store every single field that GC does - just ones we might ever want to change or show …
> Tables and models for GoCardless

- Gemfile
- Gemfile.lock
- app/controllers/api/actions_controller.rb
- app/controllers/application_controller.rb
- spec/controllers/api/actions_controller_spec.rb
- spec/requests/api/actions_spec.rb
Fun story: trying to send UA/referer parsing along with donations information breaks _260_ specs. I spent some time yesterday trying to fix those, and failed miserably. So, I'm just punting on that because I don't want to modify a bunch of your donation code right before I'm not working here any more. This will pass along the mobile and referer parameters to ActionKit and store them with action records.
> Adding referer and UA parsing on Actions and sending them to AK

- app/liquid/views/partials/_simple_footer.liquid
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
I changed 2015 to 2016 in our webpage footer copyright notice.
I also added a link to start a petition on community.sumofus.org (controlshift). We have it working in English and French, so I've got anchor texts for those languages in their yml files, but I'm leaving the anchor text intentionally blank in the German yml file because we don't have controlshift setup in German yet. So if all goes well browsers will just render an anchor with nothing in it.
> Footer date corrected and cs link added

- app/assets/javascripts/sumofus/backbone/form_methods.js
- app/assets/stylesheets/page-edit.scss
- app/controllers/form_elements_controller.rb
- app/liquid/champaign_liquid_filters.rb
- app/liquid/views/partials/_form.liquid
- app/views/form_elements/_element.slim
- app/views/forms/_add_element.slim
- app/views/forms/_preview.html.slim
- config/initializers/liquid.rb
- config/locales/champaign.en.yml
- config/locales/sumofus.de.yml
- config/locales/sumofus.fr.yml
- spec/liquid/champaign_liquid_filters_spec.rb
This PR gives campaigners the ability to add a default value to a form field for a petition or donation. It also has some copy changes and adds a new liquid filter that was needed to set the default value of the country dropdown.
> Form defaults

- config/locales/sumofus.de.yml
- spec/requests/liquid_rendering_spec.rb
If we had merged to production at the beginning of this week, we would have brought down every German page on production. The problem was this line in `sumofus.de.yml`:
```
controlshift: #intentionally left blank
```
That needed to be 
```
controlshift: "" #intentionally left blank
```
The former is not valid YML syntax. I noticed it looked funny when I looked over @edubsky's PR, but I assumed it was unconventional but acceptable because 
1) I have smoke tests that would have flagged it if it was a problem and
2) I assumed that Eoin clicked around to test that it worked in all relevant languages.
Today I loaded a German page in my dev environment and caught the error. I then looked at my smoke test to figure out how they didn't flag this on CCI, and realized that they only tested the page …
> [critical bug fix] fix liquid template smoke tests and empty german translation

- config/locales/sumofus.fr.yml
So donate follow-up pages didn't say "share the petition"
> Changed "the petition" to "the campaign"

- app/assets/javascripts/page_edit_bar.js
- app/assets/javascripts/syntax-highlighting.js
- app/assets/stylesheets/page-edit.scss
- app/views/pages/_form.slim
- app/views/pages/show.slim
- config/locales/champaign.en.yml
- db/migrate/20160418211612_add_javascript_to_page.rb
- db/schema.rb
- spec/models/page_spec.rb
It's been rather common for campaigners to want to do weird one-off tweaks to the page layout, such as removing the total signature count, changing the word signature to pledge, or prefill a field. Prefilling is now supported natively, but what's become clear is that they need a way to mess around with stuff rather than waiting on us to implement it. 
So far, this has meant using Optimizely to deliver the changes, or inserting a `<script>` tag into the HTML  pane of the WYSIWYG editor. Neither is ideal, so what I've done is added a javascript field to the page. It's hidden by default with a link to "Add javascript" below the WYSIWYG if the javascript is empty, but it displays on page load if it already has a value. The javascript gets dumped into a `<script>` tag inside of a …
> Add javascript panel to page editor to stop putting JS in WYSIWYG HTML

- app/assets/stylesheets/sumofus/components/photos.scss
- app/assets/stylesheets/sumofus/pages/share.scss
- app/liquid/views/partials/_share_page.liquid
Cleaner share page design - no background image, focus on call-to-action (rather than thanks message), and no confirmation line above.
Tested with Optimizely and works well (11% better than our current design from Agency), resulting in more clicks on share buttons. 
Result should be:
> Share page design tweaks

- app/assets/stylesheets/page-edit.scss
- app/assets/stylesheets/sumofus/components/petition.scss
- app/assets/stylesheets/sumofus/components/photos.scss
- app/assets/stylesheets/sumofus/global/typography.scss
- app/helpers/pages_helper.rb
- app/views/pages/show.slim
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
- spec/helpers/pages_helper_spec.rb
This fixes a host of small requested features -
- on twitter, the link preview wasn't loading the image because it used the wrong meta tag. this is now fixed.
- when people directly shared the link on facebook and twitter, the link preview showed the page title and body text, rather than the carefully crafted shares. We now use the most recently created facebook share, falling back to the title and description. this has a spec. 
- note: this also means a round trip or two to the DB for every page load, which may adversely affect our performance.
- the page titles on mobile were too large, often resulting in hyphenation. they are now smaller.
- there were persistent inconsistencies between paragraph spacing here and in google docs. I'm trying to fix them by stripping the previous default …
> Sharing 'n formatting

- app/controllers/api/go_cardless_controller.rb
- app/controllers/api/payment/braintree_controller.rb
- app/controllers/payment_controller.rb
- app/models/payment/go_cardless.rb
- app/services/action_queue.rb
- app/services/direct_debit_decider.rb
- app/services/manage_donation.rb
- config/routes.rb
- lib/payment_processor/clients/braintree/populator.rb
- lib/payment_processor/clients/braintree/subscription.rb
- lib/payment_processor/clients/braintree/transaction.rb
- lib/payment_processor/go_cardless/populator.rb
- lib/payment_processor/go_cardless/subscription.rb
- lib/payment_processor/go_cardless/transaction.rb
- spec/fixtures/vcr_cassettes/go_cardless_successful_subscription.yml
- spec/fixtures/vcr_cassettes/go_cardless_successful_transaction.yml
- spec/requests/api/go_cardless/go_cardless_spec.rb
Just a bunch of coding, mostly simplifications, to get the GoCardless integration a lot closer to where it should be. The state of the spec is shown below (failures are indicated by asterisks in the left column). It works for both subscriptions and transactions, and it uses the same controller action for both Braintree and GoCardless, though I'm currently doing it by inheritance to avoid changing the routes. Tomorrow, I think I'll start writing specs for the error cases. @osahyoun I've also changed the call signature for the writer methods in `go_cardless.rb` to the minimum, and I think you'll want to check those out.
```
GoCardless API
after successful redirect flow
transaction
when Member exists
creates a PaymentMethod record that stores the mandate id
leaves a cookie with the member_id …
```
> Moving GC forward

- app/assets/javascripts/configure_wysiwyg.js
- app/assets/stylesheets/sumofus/components/petition.scss
- app/assets/stylesheets/sumofus/components/photos.scss
- app/assets/stylesheets/sumofus/pages/page.scss
- app/controllers/liquid_layouts_controller.rb
- app/liquid/views/layouts/petition-without-image.liquid
- app/views/layouts/application.html.slim
- app/views/liquid_layouts/index.html.slim
- app/views/pages/analytics.slim
- app/views/pages/edit.slim
- app/views/pages/index.slim
- app/views/pages/new.slim
- spec/controllers/liquid_layouts_controller_spec.rb
This PR adds a SOU template for pages without a cover image. Ideal for page with a video as the feature or maybe like what Angus wanted with a portrait inline. Most of the actual coding was to ensure that embedded YouTube iframes properly size themselves when the page is skinnier, such as on mobile.
> Video page

- app/controllers/api/go_cardless_controller.rb
- app/services/action_queue.rb
- config/routes.rb
- lib/payment_processor/clients/braintree/error_processing.rb
- spec/controllers/api/go_cardless_controller_spec.rb
- spec/lib/payment_processor/clients/braintree/error_processing_spec.rb
- spec/lib/payment_processor/clients/braintree/subscription_spec.rb
- spec/lib/payment_processor/clients/braintree/transaction_spec.rb
- spec/models/payment/go_cardless/transaction_spec.rb
@NealJMD There are still a few failing specs, but wasn't sure how to progress. You've made some breaking changes to `Braintree::ErrorProcessing` - you're now passing it errors directly, which breaks a lot.
> Going cardless - review

- app/controllers/application_controller.rb
- spec/lib/payment_processor/currency_spec.rb
- spec/requests/api/actions_spec.rb
The [mobile detection library](https://github.com/ktaragorn/mobile_detect) we're using forces utf-8 regexes, but some user agent strings are ASCII-8BIT and can't be transcoded. This adds a test case showing the bug which fails with the old code and passes with the new code.
> fix bug where user agent headers caused encoding error

- .gitignore
lets developers use these tools easily.
> ignore gemset and version files used by rvm and rbenv.

- app/assets/stylesheets/sumofus/pages/share.scss
This helps ensure share buttons aren't pushed down too far on mobile phone screens. (I don't have local dev setup yet, but these CSS tweaks look fine when done in my browser.)
> Made share page titles smaller for mobile devices

- app/liquid/views/partials/_small_image_footer.liquid
The page-with-small-image footer copyright should be 2016, not 2015.
> 2016 copyright, not 2015

- app/services/action_queue.rb
- spec/lib/payment_processor/go_cardless/transaction_spec.rb
- spec/requests/api/go_cardless/go_cardless_spec.rb
There were two problems: 
+ the worker didn't have an up to date version of the actionkit gem - has been fixed in another PR.
+ AK donation push api needs card details! I already knew this. AK have fooled me twice.
> Send fake card details

- app/models/member.rb
- spec/models/member_spec.rb
- spec/requests/api/go_cardless/go_cardless_spec.rb
Per the email from GoCardless, we should expect GC to make a bunch of Customers for the same member. I want to add a quick request spec to this too.
> make Member -> GC Customer has_many

- app/assets/javascripts/sumofus.js
- app/assets/javascripts/sumofus/backbone/fundraiser_bar.js
- app/assets/javascripts/sumofus/ga_event_reporting.js
This will let us tell how many donors are falling off after opening the direct debit flow. I triple-checked that its using the ga API properly, but haven't been able to see events show up, presumably from URL filtering.
> track direct debit events

- app/models/payment/go_cardless.rb
- app/models/payment/go_cardless/subscription.rb
- lib/payment_processor/go_cardless/subscription.rb
- lib/payment_processor/go_cardless/transaction.rb
- spec/lib/payment_processor/go_cardless/subscription_spec.rb
- spec/lib/payment_processor/go_cardless/transaction_spec.rb
- spec/requests/api/go_cardless/go_cardless_spec.rb
- spec/requests/api/go_cardless/webhooks_spec.rb
We were failing to store some important associations on GoCardless records. This fixes it and updates the spec to ensure that we are.
> fix up bookkeeping on gocardless

- app/assets/stylesheets/sumofus/components/petition.scss
- app/assets/stylesheets/sumofus/components/photos.scss
- app/assets/stylesheets/sumofus/pages/page.scss
- app/liquid/views/layouts/fundraiser-with-small-image.liquid
- app/liquid/views/layouts/fundraiser-with-title-below-image.liquid
- app/liquid/views/layouts/petition-with-title-below-image.liquid
- app/liquid/views/partials/_full_width_header.liquid
- app/liquid/views/partials/_fundraiser_with_small_image.liquid
- app/liquid/views/partials/_mobile_title.liquid
- app/liquid/views/partials/_petition_with_small_image.liquid
- app/liquid/views/partials/_small_header.liquid
Angus requested that we stop displaying the title over the image on mobile. This implements that change, as well as allowing campaigners to choose that display for desktop for images when its important to see the whole image.
> Mobile header

- app/controllers/api/actions_controller.rb
- spec/controllers/api/actions_controller_spec.rb
and we're getting lots of errors on this - it's our busiest endpoint.
> Disable csrf for actions api, since user is not signed in.

- app/services/page_cloner.rb
- spec/services/page_cloner_spec.rb
Sondya realized that our cloned pages cloned the action counts, and there's nothing the campaigner to do to bring that number back down. This PR fixes that.
> set action_count to 0 when cloning a page

- config/routes.rb
- config/settings/production.yml
To get access to google insights for actions.sumofus.org we need to verify ownership of that domain. The common way of doing that is to upload a file to the site which google can then access. 
This PR allows any organisation deploying champaign to include a verification ID. Champaign will then generate the expected html file.
> Allow custom addition of google verification page

- app/assets/javascripts/tooltips.js
- app/views/pages/analytics.slim
@osahyoun I fixed it and tried to follow the existing pattern of triggering the tooltips via an event. However, I don't quite understand the reason for using events. I wanted to ask you why are you using events for this? Why not just run `tooltip()` on document.ready?
> Fix tooltips on analytics page

- app/assets/javascripts/sumofus/backbone/action_form.js
I don't know how we let it slip that it didn't do this before. I went to sign the Bayer Monsanto form and the internet was really slow and the button stayed red. Now it turns gray and says "processing..." in whatever language it should.
> Make petition and donation info forms disable button on submit

- app/liquid/page_plugin_switcher.rb
- app/models/page.rb
- spec/liquid/page_plugin_switcher_spec.rb
- spec/models/page_spec.rb
We decided a long time ago that the plugins should only be those from the primary layout, not those form the secondary layout. However, that's messing with Alex and Joe's sweet follow-up page innovations, so I've made it reflect the plugins in both.
If anyone remembers a good reason why we made it only the plugins from the primary layout, please say something. I remember it being a conscious decision, but can't remember any reasons that make sense now.
> Make pages reflect the plugins of the follow-up layout too

- app/services/action_builder.rb
- spec/requests/api/actions_spec.rb
- spec/services/action_builder_spec.rb
If a member has already signed a campaign in one language, we shouldn't allow them to resign on every page of that campaign. This logic should do that but it needs a spec. Hoping someone might pick this one up.
> Prevent member signing multiple petitions in campaign

- app/models/plugins/thermometer.rb
- spec/models/plugins/thermometer_spec.rb
```include ActionView::Helpers::NumberHelper``` polutes the global namespace. 
If those helpers are needed in a model, then they can be accessed through ```ActionController::Base.helpers```
> Remove include of NumberHelper into global namespace.

- app/assets/stylesheets/sumofus/pages/share.scss
- app/liquid/views/layouts/post-petition-share.liquid
- app/liquid/views/layouts/simple-post-petition-share.html
- app/liquid/views/partials/_share.liquid
- app/liquid/views/partials/_share_page.liquid
- app/liquid/views/partials/_simple_footer.liquid
- app/liquid/views/partials/_two_step_share_page.liquid
- config/locales/sumofus.de.yml
- config/locales/sumofus.en.yml
- config/locales/sumofus.fr.yml
Testing found a >25% increase in sharing rates if we asked people if they would share befoe showing them the share buttons, so that UI is going out standard to all the SumOfUs share pages.
> Change default post-petition share to use commitment gap ui

- app/services/direct_debit_decider.rb
- spec/services/direct_debit_decider_spec.rb
This fixes a bug that was displaying the direct debit option to all users, regardless of country, for pages whose fundraisers were set as `recurring_default` or `recurring_only`. Two mistakes allowed this to happen -
- The tests that should have been testing for false were testing for a value that is set to be true or false whether the page is recurring only. 
- in the tested code, I forgot that `[]` is truthy and should have called `.any?`
😞
> Fix a bug in direct debit decider that showed it too often

- app/assets/stylesheets/pages.scss
- app/controllers/featured_pages_controller.rb
- app/controllers/pages_controller.rb
- app/helpers/pages_helper.rb
- app/views/featured_pages/show.js.erb
- app/views/pages/_featured_column.slim
- app/views/pages/index.slim
- config/routes.rb
- spec/controllers/featured_pages_controller_spec.rb
- spec/helpers/pages_helper_spec.rb
Provides a toggle switch on the page's index view, allowing campaigners to organise what pages should appear on the homepage. The featured flag is searchable and sortable, so it's quick to search and filter on this attribute.
> Provide UI for toggling featured attribute on page

- app/controllers/api/members_controller.rb
- app/services/create_member_for_api_members_controller.rb
- app/services/form_validator.rb
- spec/requests/api/members_spec.rb
- spec/services/form_validator_spec.rb
- spec/services/page_updater_spec.rb
- spec/services/search/page_searcher/multiple_criterion_search/multiple_search_spec.rb
The validations on our Member model are extremely permissive. This is to allow the campaigners to put essentially whatever validation they want or don't want on the action form, and we will save it to the database. This works well, but the member signup endpoint used by the homepage needs to have some validation itself.
Rather than create a member signup form object in the database and making the endpoint count on that, I instead made the FormValidator service class accept either a form id or a hash of validations, as you can see in the controller and in the spec.
> Homepage signup

- app/controllers/api/members_controller.rb
- app/controllers/api/payment/braintree_controller.rb
- app/helpers/api/pages_helper.rb
- lib/payment_processor/braintree/webhook_handler.rb
- spec/controllers/api/payment/braintree_controller_spec.rb
- spec/helpers/api/pages_helper_spec.rb
- spec/requests/api/braintree/webhook_spec.rb
- spec/services/search/page_searcher/multiple_criterion_search/multiple_search_spec.rb
We're currently returning `200` for all webhook notifications posted by braintree. Occasionally we get a race-condition where we're trying to update a subscription that hasn't been created yet. By not returning `200`, the notification will be re-posted an hour later.
> 404 webhook

- app/assets/javascripts/plugins_toggle.js
- app/views/pages/_edit_sidebar.slim
- app/views/shared/_binary_switch.slim
Currently, the plugin on-off switches are broken on prod. Rodrigo's change to allow featured pages didn't take those switches into account, and this PR fixes that up.
> make toggle switches work for both plugin state and page publishing

- app/controllers/api/payment/braintree_controller.rb
- app/models/payment/braintree/notification.rb
- db/migrate/20160906155851_create_payment_braintree_notifications.rb
- db/schema.rb
- lib/payment_processor/braintree/webhook_handler.rb
- spec/controllers/api/payment/braintree_controller_spec.rb
- spec/factories/payment_braintree_notifications.rb
- spec/lib/payment_processor/braintree/webhook_handler_spec.rb
To keep track of ALL notifications from braintree for good book keeping and event replaying.
> Model for storing braintree webhook notifications

- app/services/page_cloner.rb
- spec/services/page_cloner_spec.rb
The PageCloner had a bug where the cloned page wasn't saved before it started duplicating associations, so if a page had no links, the first time the cloned page was saved was when the first duplicated plugin was associated with the cloned page. Because pages check for their plugins on save, the plugins were getting created twice, and cloned pages had double all the plugins.
> Fix bug where clone page double-created plugins

- Gemfile
- spec/requests/api/stateless/braintree/subscriptions_spec.rb
We use Paperclip for image uploads to S3, and while it's very convenient, it's lagging behind on its dependencies and has a hard requirement for an old version of the AWS SDK. My solution to fix this has been to use the up-to-date version for our own requirements, and install the old SDK for Paperclip. Obviously having two versions of the same gem is a little sub-optimal, but I don't want us to stick to the old sdk just because of Paperclip.
> Separately install legacy aws sdk for Paperclip

- app/controllers/email_confirmation_controller.rb
- app/controllers/payment_controller.rb
- app/services/auth_token_verifier.rb
- app/services/email_verifier_service.rb
- docker-compose.yml
- spec/factories/members.rb
- spec/requests/api/braintree/braintree_spec.rb
- spec/requests/email_confirmation_spec.rb
- spec/services/auth_token_verifier_spec.rb
Pushes messages about becoming an express donor (either account or cookie based express donor) to the AK worker queue. Also some cleanup. The custom action field needs to be added later after I get input from the analysts.
> Express donors to ak

- Gemfile.lock
- app/services/action_queue.rb
- app/services/braintree_services/one_click_service.rb
- app/services/manage_braintree_donation.rb
- spec/requests/api/braintree/braintree_spec.rb
- spec/requests/api/go_cardless/go_cardless_spec.rb
I'm still in talks with Tara and Simona on whether this implementation is sufficient. I think they have a wish to have a custom field separate cookie and account based donors, but since the user flow is identical I'm not sure whether it's possible to deliver on that. I've asked Simona if it's all right to just pass a boolean if the action is an express donation. 
I spent quite a bit of time planning something for the Braintree payment processing utilities until I realized there's a different route and controller method for one-click donations. I think we might want to do some refactoring. After adding the custom action I went to modify the specs and noticed a comment about wanting to change the implementation to not use ActionBuilder. @osahyoun could you comment on that, since it was your …
> Passes a custom action field to AK when making one click donation

- app/assets/javascripts/member-facing/backbone/sidebar.js
The sticky js seems to have started to initialize after the sidebar positioning js, so I added a check 200 ms later just to be safe. Seems to clear it up just fine.
> Fix bug where sticky sidebar flickered

- app/services/form_validator.rb
- spec/factories/form_elements.rb
- spec/services/form_validator_spec.rb
Checkboxes by default submit `'0'` which was an acceptable value for required fields. This checks against it to prevent that happening.
> Stop required checkbox in action forms accepting unchecked boxes

- lib/api/stateless/payment_helper.rb
- spec/requests/api/stateless/braintree/payment_methods_spec.rb
Some stored payment methods are stored because they're linked to subscriptions. When fetching member payment methods, we only want to return those payment methods that were stored as a result of the member's decision (payment methods with the `store_in_vault` flag set to `true`).
> Only return stored payment methods

- app/views/layouts/member_facing.slim
good catch by Paul that this was only happening in `liquid.slim`
> add facebook app id meta tag if available

- app/assets/javascripts/member-facing/backbone/fundraiser.js
- app/controllers/member_authentications_controller.rb
- app/controllers/pages_controller.rb
- app/views/plugins/fundraisers/_fundraiser.liquid
- spec/controllers/member_authentications_controller_spec.rb
- spec/controllers/pages_controller_spec.rb
- spec/javascripts/member-ui/fundraiser_spec.js
This pull request manages to get all the existing javascript tests working with the new front-end logic, making some changes to reflect the new logic. All tests are passing for both ruby and javascript, but rubocop is failing some specs from my stuff that's already in development.
However, I don't think this PR should be merged and we should release without adding a few test cases to the fundraiser_spec.js that test the logic in `submitOneClick` and `onOneClickSuccess`. It's pretty straightforward to add them like the ones I've added in this PR. I'll do it when I get in if nobody else feels like doing it.
> Fix JS tests for one-click release

- app/models/member_authentication.rb
- spec/models/member_authentication_spec.rb
- spec/models/member_spec.rb
- spec/requests/api/stateless/auth_spec.rb
- spec/requests/api/stateless/members_spec.rb
We've been authorizing unconfirmed authentication records. `authenticate` now checks that `confirmed-at` isn't `nil`.
> Check authentication has been confirmed.

- app/services/member_with_authentication.rb
- spec/services/member_with_authentication_spec.rb
The member's dashboard now only requires an email and a password (+ password confirmation) in order to register, so this PR removes the validation on `country`.
> Make country optional for MemberWithAuthentication

- Gemfile.lock
- app/models/member.rb
- app/services/action_builder.rb
- app/services/action_queue.rb
- app/services/manage_survey_response.rb
- app/services/member_updater.rb
- lib/champaign_queue.rb
- lib/champaign_queue/clients/http.rb
- spec/lib/champaign_queue/clients/http_spec.rb
- spec/services/action_builder_spec.rb
- spec/services/member_updater_spec.rb
Hey @NealJMD! here's a working version of the AK sync functionality for surveys. I still need to write a couple of tests, and define the format we're using to store and publish the survey data. 
Note: I refactored `ActionBuilder` in order to be able to reuse part of its functionality, mainly the ability to update a user from the action form params. You'll find other minor refactors and tweaks as well. 
Also, I'm not happy at all with the `ActionQueue::NewSurveyResponse` implementation, but in order to implement a good solution I would've had to rewrite the entire `ActionQueue` module, which I think we should put off for another time.
> Survey ak sync

- app/assets/javascripts/member-facing/backbone/fundraiser.js
> If I click 'Not you?' when a member is identified and make a donation as another member while having 'save my payment method' checked, it does not take me to the account creation page.
The `fundraiser.js` code did not properly reset the user when we cleared the form. Since the redirection rules take into account member state, it needed to be properly cleared in order to behave as expected.
I also tried adding a test for this, but since we don't have unit tests for javascript code (yet), testing this with E2E/integration tests is not trivial and prone to error. Therefore:
**TODO** create unit tests for JavaScript code.
Delivers [PT#132203247](https://www.pivotaltracker.com/story/show/132203247)
> Reset the member when user clears the form

- app/services/action_builder.rb
- app/services/manage_action.rb
- circle.yml
- lib/payment_processor/braintree/one_click.rb
- spec/requests/api/braintree/braintree_spec.rb
`braintree/oneclick` wasn't passing ` is_recurring` to the `ManageAction`, nor were `extra_attrs` being properly defined. This block the class from correctly setting the `donor_status` field on `Member`.
Delivers [PT#132154343](https://www.pivotaltracker.com/story/show/132154343)
> Correctly pass and handle recurring flag for one click payments

- app/admin/action.rb
- app/admin/donation_band.rb
- app/admin/image.rb
- app/admin/language.rb
- app/admin/link.rb
- app/admin/liquid_layout.rb
- app/admin/liquid_partial.rb
- app/admin/member.rb
- app/admin/page.rb
- app/admin/pages_tag.rb
Our Active Admin interface used some out-of-the-box interfaces that made sense before launch, but once our database grew, were completely untenable. This included things like dropdown selectors with every single member listed in them. This remedies those things, and should have our ActiveAdmin not-timing-out again as soon as its deployed.
> Fix Active Admin

- app/controllers/api/stateless/braintree/subscriptions_controller.rb
- app/models/payment/braintree/subscription.rb
- app/models/payment/go_cardless/subscription.rb
- app/services/go_cardless_cancellation_service.rb
- spec/models/payment/braintree/subscription_spec.rb
- spec/models/payment/go_cardless/subscription_spec.rb
- spec/requests/api/stateless/braintree/subscriptions_spec.rb
- spec/requests/api/stateless/go_cardless/subscriptions_spec.rb
This PR is ready to review but depends on https://github.com/SumOfUs/champaign-ak-processor/pull/78, which depends on https://github.com/SumOfUs/actionkit_connector/pull/11.
> Pushes a cancellation message to the AK queue when a subscription gets cancelled

- app/assets/javascripts/application.js
- app/assets/javascripts/campaigner-facing/collection_editor.js
- app/assets/javascripts/campaigner-facing/survey_editor.js
- app/assets/javascripts/member-facing/backbone/notification.js
- app/assets/javascripts/member-facing/backbone/survey.js
- app/assets/stylesheets/campaigner-facing/common.scss
- app/assets/stylesheets/campaigner-facing/page-edit.scss
- app/assets/stylesheets/member-facing/form.scss
- app/assets/stylesheets/member-facing/survey.scss
- app/controllers/form_elements_controller.rb
- app/controllers/plugins/surveys_controller.rb
- app/liquid/views/partials/_survey_form.liquid
- app/models/form_element.rb
- app/models/plugins/survey.rb
- app/views/plugins/surveys/_customize_form.slim
- app/views/plugins/surveys/_form.slim
- app/views/plugins/surveys/_survey.liquid
- app/views/plugins/surveys/add_form.js.erb
- circle.yml
- config/routes.rb
- db/migrate/20161018213050_migration_add_position_to_forms.rb
- db/schema.rb
- spec/controllers/form_elements_controller_spec.rb
- spec/models/plugins/survey_spec.rb
- spec/requests/form_elements_spec.rb
This is the last round of edits for the survey tool. It makes a bunch of changes -
* survey plugins auto-create a form with an email field when the survey is created
* survey forms can be re-ordered
* if the answers to the first section of a survey are included in the link as URL params, the first section is submitted on page load
* visual polish
> Survey last features

- app/views/layouts/generic.slim
Notes:
- I'm not sure if this template is used for any other pages than the member registration page, but as it's member-facing I assume we want the snippet there (and I want it to test on the member registration page)
- Presumably the Optimizely snippet should be a setting, rather than hard coded into a partial, but I'm leaving that
> Optimizely snippet into member registration page

- app/services/page_service.rb
- spec/services/page_service_spec.rb
We want the pages API to sort by the most recently updated campaigns, not most recently created, and we want the same limits interface for featured ones as unfeatured ones.
> Make pages api show 30 most recent

- lib/payment_processor/braintree/one_click.rb
- spec/requests/api/braintree/braintree_spec.rb
We're presently forgetting to associate a subscription with the action that created it.
> Associate action with subscription.

- lib/champaign_queue.rb
- lib/champaign_queue/clients/sqs.rb
- lib/payment_processor/braintree/webhook_handler.rb
- spec/lib/champaign_queue/clients/sqs_spec.rb
- spec/lib/champaign_queue_spec.rb
- spec/lib/payment_processor/braintree/webhook_handler_spec.rb
- spec/requests/api/braintree/webhook_spec.rb
We're processing a subscription transaction before the subscription record has been created on AK. This PR delays the processing of any webhook events by 2 minutes.
> Pass delay_seconds to SQS client

- app/controllers/plugins/petitions_controller.rb
- app/controllers/plugins/surveys_controller.rb
- app/models/payment/go_cardless.rb
- app/models/plugins.rb
- app/models/plugins/has_form.rb
- app/services/form_duplicator.rb
- app/services/form_element_builder.rb
- app/services/manage_donation.rb
- app/services/member_updater.rb
- app/services/page_cloner.rb
Hey team! I replaced some `save` and `update` calls with their matching bang versions where I thought appropriate. Again, I strongly believe that the bang version should we used in all cases where an error is not expected to happen. And if an error is part of the regular user flow, then we should be checking the result of the call to `save` or `update` and act accordingly. 
There's a chance that these changes break some existing functionality, in places where errors are happening and we're just missing them. That's why I'm asking you to review this thoroughly, signing off every change separately.
As an extra I also replaced the `update_attributes` call with the newer shorter nicer version `update` in a couple places.
> Raise errors on unexpected failure

- app/models/campaign.rb
- app/models/page.rb
- app/views/api/pages/index.json.jbuilder
- app/views/api/pages/show.json.jbuilder
- spec/models/campaign_spec.rb
- spec/models/page_spec.rb
- spec/requests/api/pages_spec.rb
This is to make the tiles on the homepage include the action count of the whole campaign, not just that page.
> makes pages JSON API report campaign_action_count

- Gemfile
- Gemfile.lock
- app/controllers/api/payment/braintree_controller.rb
- app/controllers/pages_controller.rb
- app/services/action_params_builder.rb
- config/environments/test.rb
- config/locales/member_facing.en.yml
- config/routes.rb
- lib/champaign_queue.rb
- lib/payment_processor/braintree/one_click.rb
- lib/payment_processor/braintree/one_click_from_uri.rb
- spec/factories/liquid_layouts.rb
- spec/features/express_donations/email_one_click_spec.rb
- spec/fixtures/vcr_cassettes/feature_member_email_donation.yml
- spec/fixtures/vcr_cassettes/feature_one_click_cookie.yml
- spec/fixtures/vcr_cassettes/feature_store_card_in_vault.yml
- spec/rails_helper.rb
Allows campaigners to email 'one click' donation links. 
If a member clicking through has a payment method cookie or is logged in, then the donation will be processed immediately, otherwise they'll be presented with the original campaign page view. 
To enable one-click, URIs must take this format:
`/a/page-slug?one_click=true&amount=10&currency=GBP`
> (True) oneclick

- .gitignore
- .rubocop.yml
- app/assets/javascripts/member-facing/backbone/fundraiser.js
- app/controllers/api/payment/braintree_controller.rb
- app/services/braintree_services/subscription_builder.rb
- app/services/braintree_services/transaction_builder.rb
- app/views/api/payment/braintree/one_click.json.jbuilder
- lib/payment_processor/braintree/one_click.rb
- spec/fixtures/vcr_cassettes/express_donations_invalid_payment_method.yml
- spec/requests/api/braintree/braintree_spec.rb
Closes PT stories: #133020257 and #130729249
One click endpoint now returns a `422 Unprocessable Entity` if the braintree transaction with the stored payment method results in a failure (`.success? == false`). From the `ErrorResult` object, we send the client a payload (for future use) with the following shape:
```json
{
"success": false,
"message": "An error message from Braintree",
"errors": [],
"params": {}
}
```
> Handle Braintree errors in express donations

- lib/payment_processor/braintree/one_click.rb
- spec/requests/api/braintree/braintree_spec.rb
There was a bug that was causing express donations to be charged in the default currency and not being settled (only authorised) 
We now pass `merchant_account_id` and `submit_for_settlement` in one click donations.
> Express donations bugfix: currency and submit for settlement.

- .rubocop.yml
- app/assets/javascripts/member-facing.js.erb
- app/assets/javascripts/member-facing/backbone/fundraiser.js
- app/assets/javascripts/member-facing/redirectors.js
- app/assets/stylesheets/member-facing/fundraiser.scss
- app/controllers/api/actions_controller.rb
- app/controllers/api/survey_responses_controller.rb
- app/controllers/application_controller.rb
- app/controllers/member_authentications_controller.rb
- app/controllers/payment_controller.rb
- app/controllers/reset_passwords_controller.rb
- app/views/plugins/fundraisers/_fundraiser.liquid
- package.json
- spec/controllers/member_authentications_controller_spec.rb
- spec/features/express_donations/email_one_click_spec.rb
- spec/javascripts/member-ui/fundraiser_spec.js
- spec/liquid/liquid_renderer_spec.rb
Extracted redirect logic into Redirector services in redirectors.js. Fundraiser.js doesn't handle the redirect logic anymore, instead what it does is simply publish an event `fundraiser:success` that should be captured by the view loading this widget. 
I also refactored the member authentication flow. It used to require a page_id param to be passed. Now I've replaced `page_id` with a new optional param `follow_up_url`. If `follow_up_url` is not passed, then the user is redirected to the home page after signing up.
This PR depends on these changes to the templates on sou-assets:
https://github.com/SumOfUs/sou-assets/pull/11
> Fundraiser.js, member registration and localization refactor.

- app/models/payment/braintree.rb
- app/models/payment/braintree/transaction.rb
- lib/payment_processor/braintree/webhook_handler.rb
- spec/lib/payment_processor/braintree/webhook_handler_spec.rb
- spec/models/payment/braintree/transaction_spec.rb
- spec/requests/api/braintree/webhook_spec.rb
Missing logic to handle failed GoCardless subscription charges. Looking into it now.
> Handle failed subscription charges - Braintree

- app/services/action_queue.rb
- spec/requests/api/braintree/braintree_spec.rb
Posts to ActionKit quietly fail with lowercase currency.
> Upcase currency when posting to AK

- app/models/payment/go_cardless/transaction.rb
- config/environments/production.rb
- lib/payment_processor/braintree/webhook_handler.rb
- lib/payment_processor/go_cardless/webhook_handler/process_events.rb
- spec/lib/payment_processor/braintree/webhook_handler_spec.rb
- spec/requests/api/braintree/webhook_spec.rb
- spec/requests/api/go_cardless/webhooks_spec.rb
There are a couple changes here:
- I tidied up `PaymentProcessor::Braintree::WebhookHandler` a little and would particularly appreciate an eye on the changes there.
- After realizing today that the log feed on staging for the webhooks coming in from Braintree are really not very useful, I've changed the logging in `WebhookHandler`. We are currently only getting the request path, controller, action and parameters. The unparsed `bt_payload` field is [taking a *ton* of log space](https://papertrailapp.com/systems/champaign-staging/events?q=bt_payload&focus=740269293195022337) while providing no information at all, and we handle all the webhooks through the same path, so there really is not much information about what was being processed. I filtered the bt_payload parameter on Lograge and am …
> Failed gc subscription charges

- app/frontend/components/AmountSelection/AmountSelection.js
- app/frontend/containers/FundraiserView/FundraiserView.js
- app/frontend/state/fundraiser/reducer.js
I updated the AmountsSelection component to support the new donation bands format.
I'm not sure how are we expecting to set the donation bands using this format. `champaign.personalization.donationBands` seems to be using the plain array format.
> DonationBands new format WIP

- app/models/image.rb
- circle.yml
- spec/support/paperclip.rb
+ Reduce quality for all image styles
+ Turn to jpg for medium and large
These changes reduced the image at https://actions.sumofus.org/a/segolene-royal-defendez-les-abeilles-contre-les-lobbies-de-l-industrie-chimique from 2.2mb to 100k, without noticeably affecting image quality on a retina display.
> Better image size handling

- app/models/form_element.rb
- spec/models/form_element_spec.rb
Per data team's request, dropdowns and multiple choice are now prefixed by `action_dropdown_` and `action_choice_` respectively.
> give dropdown and multiple choice qs action_ prefixes

- app/models/payment/braintree/transaction.rb
- app/models/payment/go_cardless/transaction.rb
- spec/lib/payment_processor/braintree/webhook_handler_spec.rb
- spec/models/payment/braintree/transaction_spec.rb
- spec/requests/api/braintree/webhook_spec.rb
- spec/requests/api/go_cardless/webhooks_spec.rb
* Push created_at into subscription charge events
* Adhere to the only time format AK supports for created_at
* Adhere to the only time format AK supports for created_at
> Change the time format for the created_at field. (#811)

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/uris_controller.rb
- app/liquid/liquid_renderer.rb
- spec/controllers/pages_controller_spec.rb
- spec/liquid/liquid_renderer_spec.rb
- spec/requests/uris_spec.rb
This PR mainly refactors the code in LiquidRenderer, simplifying a couple of methods, removing another few, and pushing some logic down to the Cache class. I think there's a lot to be done to improve the controllers code (Pages & Uris), but i'll take a stab at those at another time.
> LiquidRenderer refactor

- spec/requests/liquid_rendering_spec.rb
The `Liquid page rendering` spec file is getting slower as we create more liquid templates. This PR moves layout seeding into a `before all` block, reducing the run time from 35 to 9 seconds on my machine.
> Seed with layouts before running all spec.

- app/controllers/email_confirmation_controller.rb
- spec/requests/email_confirmation_spec.rb
`GET /email_confirmation` is an easy endpoint to spam. This fix will quieten down the errors:
https://sumofus.airbrake.io/projects/132582/groups/1808966452919560309?tab=overview
> Raise 404 if email not present or member not found

- app/controllers/api/pages_controller.rb
- app/controllers/member_authentications_controller.rb
+ respond only to json request on `show#/api/pages`
+ skip `verify_authenticity_token` for new account confirmations. It's not needed here, so ditching as it raising quite a lot
> Small fixes

- app/services/payment_method_fetcher.rb
- spec/services/payment_method_fetcher_spec.rb
Currently members can see cancelled payment methods when making a donation.
> Don't return cancelled payment methods

- app/frontend/components/ExpressDonation/ExpressDonation.js
- app/frontend/components/MemberDetailsForm/MemberDetailsForm.js
- app/frontend/components/Payment/Payment.js
- app/frontend/components/Stepper/Step.scss
- app/frontend/components/Stepper/StepWrapper.js
- app/frontend/components/Stepper/Stepper.scss
- app/frontend/components/SweetSelect/SweetSelect.scss
- app/frontend/containers/FundraiserView/FundraiserView.js
- app/frontend/containers/FundraiserView/FundraiserView.test.js
- app/frontend/state/fundraiser/actions.js
- app/frontend/state/fundraiser/reducer.js
This addresses [this ticket](https://www.pivotaltracker.com/story/show/137512157) by pushing the `submitting` state into the store, and then completely changing the interface when it's true.
> show interstitial when processing donation

- app/controllers/api/actions_controller.rb
- app/controllers/api/survey_responses_controller.rb
- app/controllers/application_controller.rb
- app/controllers/member_authentications_controller.rb
- app/controllers/payment_controller.rb
- app/frontend/components/DonationBands/DonationBands.js
- app/frontend/components/MemberDetailsForm/MemberDetailsForm.js
- app/frontend/containers/FundraiserView/FundraiserView.js
- app/frontend/containers/FundraiserView/FundraiserView.test.js
- app/views/layouts/generic.slim
- config/locales/member_facing.de.yml
- config/locales/member_facing.en.yml
- config/locales/member_facing.fr.yml
- spec/controllers/member_authentications_controller_spec.rb
- spec/requests/localization_spec.rb
[The bug](https://www.pivotaltracker.com/story/show/137511937) that Paul reported with German translations on an English page was because the form_id was being submitted in place of the page_id. In fixing that though, I uncovered plenty of issues with the localization both with react and without, and fixed everything I found.
> Translation fixes

- config/locales/member_facing.en.yml
Transifex (our translation tool) doesn't like blank translations, which causes issues (and requires manual copy/pasting) when updating yml files. These placeholder values are just to stop that happening, given they should not actually be used on production (instead, values from sou-assets are used as I understand it)
> Inserting some placeholders

- app/helpers/pages_helper.rb
- app/views/pages/_show.slim
- spec/helpers/pages_helper_spec.rb
We're currently setting a family of `image` related og meta tags, which FB doesn't use. I'm pretty sure (from the [docs](https://developers.facebook.com/docs/sharing/webmasters#markup)) that they only require a single `og:image` meta tag that points to the image's file location.
> Only necessary to set og:image for FB

- app/services/action_builder.rb
- spec/services/action_builder_spec.rb
This will help us track sharing credit from forwarded emails too, and enable the share-success notification emails.
> Populate referrer_email from referring_akid if no referrer_id present

- app/models/page.rb
- app/services/page_cloner.rb
- spec/factories/pages.rb
- spec/services/page_cloner_spec.rb
There was a bug where cloned pages' cloned facebook shares referenced the shares of the original page, not the cloned page. This meant that as soon as the cloned page was saved for the first time, it eliminated the facebook shares' images. This fixes that.
> fix share cloning to use cloned page's images

- app/models/payment/braintree/transaction.rb
- lib/payment_processor/braintree/webhook_handler.rb
- spec/lib/payment_processor/braintree/webhook_handler_spec.rb
- spec/models/payment/braintree/transaction_spec.rb
- spec/requests/api/braintree/webhook_spec.rb
Right now we're updating some subscriptions manually through the Braintree console. This means that the payments coming through to those subscriptions come in with a different amount than what the subscription is associated with, and this isn't reflected on the data in AK in that if you don't override the amount parameter, it just fetches the amount from the price of the subscription.
> Pass amount in the event pushed to the queue on braintree subscription payments

- app/controllers/clone_pages_controller.rb
- app/models/plugins/has_form.rb
- app/services/default_form_builder.rb
- app/services/page_cloner.rb
- app/views/clone_pages/new.html.slim
- config/locales/champaign.en.yml
- db/seeds.rb
- spec/controllers/clone_pages_controller_spec.rb
- spec/services/default_form_builder_spec.rb
- spec/services/page_cloner_spec.rb
This gives an option in the cloning interface to allow people to change the language, and convert the language of the accompanying forms.
> Clone form

- config/initializers/formtastic_ext.rb
Member services are currently unable to edit member details because active admin crashes when trying to render the edit form. We recently added a new attribute of type JSONB which formtastic has no matching class definition.  This PR defines that missing type.
> Extend formtastic with missing field type

- .rubocop.yml
- app/frontend/components.js
- app/frontend/components/CallTool/Form.js
- app/frontend/containers/CallToolView/CallToolView.js
- app/models/plugins/call_tool.rb
- app/services/page_cloner.rb
- app/views/plugins/call_tools/_call_tool.liquid
Updated Call Tool plugin and component to handle different flows. I added a `target_by_country` which changes the way the call tool works
* If `target_by_country` is enabled, then the call tool works as it previously did. When a country is selected from the dropdown, a target belonging to that target is randomly selected.
* If `target_by_country` is disabled, when a country is selected a target is randomly selected. Target countries are not considered here. The dropdown is there to prefill the country code in the phone number field.
> Call tool.target by country

- app/controllers/pages_controller.rb
- spec/controllers/pages_controller_spec.rb
Put an end to the 500s being raised whenever a JSON request is made to `pages#show` (mainly by scraping bots). See https://sumofus.airbrake.io/projects/132582/groups/1809838475682145060
#894
> Accept only HTML requests to pages#show

- app/frontend/components/AmountSelection/AmountSelection.js
- app/frontend/components/AmountSelection/AmountSelection.test.js
- app/frontend/components/DonationBands/DonationBands.js
- app/frontend/components/FieldShape/FieldShape.js
- app/frontend/components/Payment/Payment.js
- app/frontend/containers/FundraiserView/FundraiserView.js
- app/frontend/containers/FundraiserView/FundraiserView.test.js
- app/frontend/state/fundraiser/reducer.js
- app/frontend/util/ChampaignAPI.js
- package.json
- yarn.lock
- Proceed button always shown
- Proceed button disabled if no amount or featured amount present
- Proceed button logic removed from DonationBands component
- Remove toggle logic for proceed button
Tests have been updated to reflect new functionality.
> Preselected Amounts: Simplify Step 1 (Amount Selection)

- .rubocop_todo.yml
- app/controllers/pages_controller.rb
- app/helpers/pages_helper.rb
- app/services/search/page_searcher.rb
- app/views/pages/_search.slim
Loading all the pages is starting to drag quite a bit on production, so this change loads the last 500 pages by default, and lets campaigners set whether they wish to load 500, 1000, or unlimited. It also cleans up some of the search code, which was written quite early, and it cleans up the appearance of the URL params for searching.
> Clean up page searcher and add limit to page search params

- app/controllers/pages_controller.rb
- app/views/pages/analytics.slim
This is just a stand-in for Emma and David to be able to see the call counts for the next few days; Rodrigo is working on a much more fully featured version.
> Add super basic call count to call tool pages

- Gemfile
- Gemfile.lock
- app/controllers/api/stateless/location_controller.rb
- config/routes.rb
- lib/api/exceptions.rb
- spec/rails_helper.rb
- spec/requests/api/stateless/location_spec.rb
**Why?**
We need to run some experiments from other sumofus.org domains (e.g. homepage), but we need to tap into Champaign's logic. In this case, we need location and currency information. Since getting the location blocks the request, it should be used sparingly.
**Details**
`GET /api/stateless/location` responds with `request.location` (Geocoder), extending it
with the currency for that country code, using `Donations::Utils.currency_from_country_code` for consistent behaviour with champaign pages.
When there’s a timeout (or when the location can’t be determined), we return a 504 Gateway Timeout error.
> Add location endpoint and specs

- app/controllers/api/calls_controller.rb
- app/frontend/containers/CallToolView/CallToolView.js
- app/frontend/util/ChampaignAPI.js
- app/models/call.rb
- app/models/call_tool/target.rb
- app/models/plugins/call_tool.rb
- app/services/call_creator.rb
- config/locales/member_facing.en.yml
- db/migrate/20170301193907_add_target_to_calls.rb
- db/migrate/20170304151306_migrate_call_target_format.rb
- db/migrate/20170304165947_remove_target_index_from_calls.rb
- db/schema.rb
- spec/factories/calls.rb
- spec/models/call_spec.rb
- spec/requests/api/calls_spec.rb
- spec/services/call_creator_spec.rb
This refactor solves a couple issues we used to have with how we were managing call tool targets.
* Before this PR, the `Call#target_index` field would store an integer that then would be used in `CallTool.targets[target_index]` in order to know the target of a call. If a new targets CSV was uploaded, then the existing calls `#target_index` field would get outdated. 
* Another issue that was fixed is the following. The front end form used to send a `target_index` field when creating a call. This field was used to find the target for the call using `CallTool.targets[target_index]`, and again, if the targets where updated then the member might be calling a different target than the expected one. 
**To fix those two issues I implemented the following:**
* When a call is created I'm storing …
> Call tool refactor

- app/assets/javascripts/dependencies.js
- app/assets/javascripts/member-facing.js.erb
- app/assets/javascripts/member-facing/backbone/fundraiser.js
- app/assets/javascripts/vendor.js
- app/views/layouts/member_facing.slim
- app/views/plugins/fundraisers/_fundraiser.liquid
- config/initializers/assets.rb
- db/schema.rb
Part 1 of 4 in #902
This moves script tags to the bottom of `<body>`. This change would normally cause a flicker fundraiser form until the plugin's `changeStep` fn runs, so I'm hiding all script dependent panels by default (`changeStep` runs as soon as we initialise the plugin so it will _always_ unhide the right panel on init), and hiding the top bar (where the stepper is) and showing on init. 
There's a new file `app/assets/javascripts/dependencies.js`, that takes care of loading jQuery in `<head>`. The only other script that is loaded in the `head` is optimisely, for pages that have it enabled.
Everything else is loaded _after_ the `= yield`.
> Optimise loading of member-facing scripts

- app/frontend/state/fundraiser/reducer.js
- yarn.lock
I was passing `state.currency` to pick the featured amount instead of `action.payload`, which meant the featured amount selected corresponded to the previous currency's donation band.
This was not caught during testing because all donation bands had the same amounts (so it always matched an amount).
> Fix preselected amounts currency change bug.

- .rubocop_todo.yml
- app/assets/javascripts/application.js
- app/assets/javascripts/campaigner-facing/actions_editor.js
- app/controllers/api/actions_controller.rb
- app/controllers/api/pages_controller.rb
- app/controllers/pages_controller.rb
- app/models/action.rb
- app/models/page.rb
- app/services/action_collator.rb
- app/views/pages/_settings_form.slim
- app/views/pages/actions.html.slim
- config/locales/champaign.en.yml
- config/routes.rb
- db/migrate/20170222221621_add_publish_to_actions.rb
- db/schema.rb
- spec/controllers/api/actions_controller_spec.rb
- spec/controllers/api/pages_controller_spec.rb
- spec/requests/api/pages_spec.rb
- spec/routing/api/actions_routing_spec.rb
- spec/services/action_collator_spec.rb
This pull request does several things in the service of making actions API readable on Champaign.
- it makes an API endpoint to read actions from a page if the page allows it
- it creates an interface in the pages edit settings pane to allow actions to be read, either with default published or default hidden
- it makes an interface in `/pages/:slug/actions` to hide bad actions from a page that has them default shown, or to show actions from a page that has them default hidden
I started this work for the Shopify employee poaching campaign, but that page has been put on the back burner for the time being. However, I thought it was worth finishing up this work as I foresee it as useful in the near future.
> Publish actions

- lib/payment_processor/braintree/one_click_from_uri.rb
OneClickFromUri was checking expiration date on all payment methods but
only credit / debit cards will have one (in the form of MM/YYYY).
We're now picking the most recently created "stored" and "active"
payment method, or returning nil.
The following error was triggered when trying to use expiration dates on
paypal payment methods:
```
[2017-04-11T16:34:29.450332 #6]  INFO -- : method=GET path=/a/beekeepers-bayer format=html controller=pages action=show status=500 error='NoMethodError: undefined method `to_date' for nil:NilClass' duration=15.12 view=0.00 db=9.44 params={"akid"=>"29405.7350357.ineo4F", "amount"=>"5", "currency"=>"GBP", "one_click"=>"true", "rd"=>"1", "source"=>"fwd", "t"=>"67", "id"=>"beekeepers-bayer"} time=2017-04-11 16:34:29 +0000 exception=["NoMethodError", "undefined …
```
> Fix one-click from URI error

- Gemfile
- Gemfile.lock
Context: 
https://github.com/airbrake/airbrake/issues/679#issuecomment-282472603
> Locked airbrake-ruby to 1.7.1 to remove warnings

- app/frontend/components/CallTool/Form.js
- app/frontend/containers/CallToolView/CallToolView.js
- app/frontend/containers/EmailTargetView/EmailTargetView.js
- app/models/plugins/call_tool.rb
- app/views/plugins/call_tools/_form.slim
- config/locales/champaign.en.yml
- db/migrate/20170419205020_add_allow_manual_target_selection_to_plugins_call_tool.rb
- db/schema.rb
When the feature is enabled in a page with the Caller template, it displays a dropdown with the list of targets for the selected country. The user must select a country and the page must also be configured to target by country.
> [Call tool] Allow manual target selection

- app/frontend/components/CallTool/Form.js
- config/locales/member_facing.de.yml
- config/locales/member_facing.en.yml
- config/locales/member_facing.fr.yml
NOTE: Find a more context-independent word for targets (we're using
minister in this case because of our current use case, but we might
want to use it for other types of targets). Perhaps we might scrap
this solution and develop a better "target_by_postal_code" feature.
> Use different text on dropdown label

- app/assets/javascripts/member-facing/backbone/action_form.js
- app/assets/javascripts/member-facing/backbone/survey.js
- app/controllers/api/actions_controller.rb
- app/controllers/api/email_targets_controller.rb
- app/controllers/api/survey_responses_controller.rb
- app/frontend/components/MemberDetailsForm/MemberDetailsForm.js
- app/liquid/liquid_renderer.rb
- app/services/action_builder.rb
- app/views/plugins/fundraisers/_fundraiser.liquid
- app/views/plugins/petitions/_petition.liquid
- spec/liquid/liquid_renderer_spec.rb
- spec/services/action_builder_spec.rb
Currently, when someone shares one of our pages with a ShareProgress button, the URL they share is of the form `http://sumof.us/309191623t?referrer_id=14282164`. This is fine for facebook, but uses excessive characters on twitter and the `referrer_id` looks weird. This PR will make it work with referrer_id or rid so that the URLs can have the form `http://sumof.us/309191623t?rid=14282164`.
I'm looking to get this live on prod by tomorrow :D
> Allow referring_id to be passed as rid

- config/environments/production.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
I updated the `cloudfront_url` settings to `asset_host` for two reasons:
* The cloudfront_url setting is being used to set the asset host url, and it's nothing more than a URL. So, naming it after the service we particularly use to server assets doesn't make sense.
* In production we use `Settings.cloudfront_url` while on dev and test we use `Settings.asset_host`. I think it's a good idea to have all environments use the same option name for consistency
**Important** I also renamed the env var from CLOUDFRONT_URL to ASSET_HOST, so if we merge this we need to remember to rename that env var when deploying.
> Renamed cloudfront_url  to asset_host for consistency

- app/assets/javascripts/member-facing/backbone/survey.js
- app/views/plugins/surveys/_form.slim
- app/views/plugins/surveys/_survey.liquid
- config/locales/champaign.en.yml
- db/migrate/20170626194936_add_auto_advance_to_plugins_surveys.rb
- db/schema.rb
Adds a missing feature to the survey tool (which I need for a survey we're sending tomorrow) to allow the auto-advance feature to be turned off. I've checked it on staging and it looks good.
> allow survey auto-advance to be turned off

- app/javascript/components/ExpressDonation/ExpressDonation.js
- app/javascript/components/Payment/Payment.js
- app/javascript/fundraiser/FundraiserView.js
- app/javascript/fundraiser/FundraiserView.test.js
- app/javascript/packs/email_target.js
- app/javascript/packs/fundraiser_plugin.js
- app/javascript/packs/member_facing.js
- app/javascript/state/fundraiser/actions.js
- app/javascript/state/fundraiser/helpers.js
- app/javascript/state/fundraiser/reducer.js
- app/javascript/state/index.js
- app/javascript/state/page/reducer.js
- app/javascript/state/reducers.js
- app/javascript/types.js
- flow-typed/npm/query-string_v4.x.x.js
With the last query string parameters bugfix, I introduced a new bug that always overrode the member's currency (set by location) if there was no currency parameter in the query string. This re-introduces the fallback mechanism, as well as it simplifies the fundraiser reducer. 
I've eliminated the `parse_champaign_data` from the reducer to be more explicit (now using individual actions for each group of properties). Currency is now always set via the `change_currency` action. This also introduces a new action: `initialize_fundraiser`, which initializes the component's store with a select number of properties instead of _all_ properties passed as payload. Grabbing all properties isn't declarative enough and can lead to a situation (like the one which caused this bug) where a developer …
> Correctly set currency in Fundraiser Component

- config/locales/member_facing.de.yml
- config/locales/member_facing.en.yml
- config/locales/member_facing.fr.yml
Local translations take precedence over external_assets translations so we have to delete these in order for the other ones to take effect. This fixes the following bug: https://www.pivotaltracker.com/story/show/148286787
> Delete home_url from translations

- app/controllers/action_kit_controller.rb
- app/controllers/pages_controller.rb
- app/javascript/campaigner_facing/page.js
- app/lib/action_kit/client.rb
- app/lib/action_kit/helper.rb
- app/models/page.rb
- config/settings/development.yml
- spec/controllers/action_kit_controller_spec.rb
- spec/controllers/pages_controller_spec.rb
- spec/lib/action_kit/client.rb
- spec/lib/action_kit/helper_spec.rb
- spec/models/page_spec.rb
This PR addresses several long-standing issues with Champaign, some serious, some cosmetic, all of them related to slugs.
- We never had an actual validation of unique slugs on the Page model, instead relying on friendly_id. Unfortunately, that has proven inadequate, leading to a couple very confused campaigners trying to understand how their page suddenly had no content or actions. This adds that model validation
- When new pages were created, we did a pre-check against ActionKit that the slug was unique. This check no passes only if the page is unique on both ActionKit AND Champaign.
- That same ActionKit check previously required AK credentials, and made it impossible to make pages without AK credentials. This PR removes that requirement, skipping the AK check if no AK credentials are …
> Slug better

- app/views/layouts/member_facing.slim
The favicon hasn't been showing up on member-facing pages since the Rails 5 upgrade. I found it only doesn't find it if it's called `favicon.ico`, otherwise it finds it fine. I've subsequently changed it. Accompanied by a PR on sou-assets.
> fix the favicon loading in rails 5

- app/models/call_tool/target.rb
- app/models/plugins/call_tool.rb
- circle.yml
- spec/factories/plugins_call_tools.rb
- spec/fixtures/call_tool_data.csv
- spec/models/call_tool/target_spec.rb
- spec/services/targets_parser_spec.rb
`country_name=` was being called on every instantiation, and no matter the value of `country_name` or `country_code`, it was calling `ISO3166::Country.find_country_by_name`. Now that method is only called on CSV upload.
> fix terrible load time on CallTool::Target

- Gemfile
- Gemfile.lock
- config/boot.rb
https://github.com/Shopify/bootsnap
Speeds up rails boot time by 50% per README. My test was even faster:
```
➜ rod:~/code/sou/champaign(development)% time rails r "puts 'helo'"
helo
rails r "puts 'helo'"  5.02s user 1.98s system 94% cpu 7.369 total
➜ rod:~/code/sou/champaign(development) ✗% time rails r "puts 'helo'"
helo
rails r "puts 'helo'"  2.78s user 0.50s system 120% cpu 2.714 total
```
> Speed up boot time by installing bootnstrap

- app/javascript/components/CallTool/CallToolDrillDown.js
- app/javascript/components/CallTool/CallToolDrillDown.test.js
Fixes a bug where empty filters don't match any targets and the result is an empty array of "matching" targets.
> Omit Call Tool filters with empty values

- app/javascript/components/Payment/Payment.js
- app/javascript/components/Payment/PaymentTypeSelection.js
- app/javascript/fundraiser/FundraiserView.test.js
- app/javascript/packs/fundraiser.js
- app/javascript/packs/member_facing.js
- app/javascript/state/fundraiser/actions.js
- app/javascript/state/fundraiser/helpers.js
- app/javascript/state/fundraiser/reducer.js
- app/javascript/state/fundraiser/types.js
- app/javascript/state/index.js
- app/javascript/state/reducers.js
This is for a fundraising experiment. We want to be able to pass a `dd_only=1` query parameter in a test that will disable paypal / card payment methods. This simply adds some functionality with some fallback logic (e.g. when the member is not in a direct debit country). The rest of this experiment will be done via `optimizelyHook()`.
I've also moved flow types to their own file around to make fundraiser related `app/javascript/state/*` files easier to read.
> Allow only displaying direct debit as a payment method

- app/javascript/components/DonationBands/DonationBandButton.js
Removes currency normaliser which was displaying all dollar currencies (cad, nzd and aud) as USD.
> Fixes currency display bug

- app/javascript/state/fundraiser/reducer.js
I was ignoring the payload value when handling the `set_direct_debit_only` action.
> Fix DirectDebit countries showing only DirectDebit

- app/javascript/components/EmailEditor/EmailEditor.js
The `EmailEditor` component was parsing the editable body.
> Fix email tool replacing new lines with "<br />"

- app/lib/encoding_picker.rb
- app/services/call_tool/plugin_updater.rb
- app/services/email_tool/plugin_updater.rb
Attempt UTF-8 then fallback to ISO-8859-15. Since all ISO-8859 charsets are ASCII-8BIT compatible, they're a good fallback (compatible with Windows-1252). I've chosen ISO-8859-15 since it supports a range of latin chars: accents, tildes, etc.
How could we test this?
> UTF-8 invalid charset

- app/javascript/components/EmailEditor/EmailEditor.js
- app/javascript/email_tool/EmailToolView.js
- app/javascript/packs/email_tool.js
- app/views/plugins/email_pensions/_email_pension.liquid
- app/views/plugins/email_tools/_email_tool.liquid
- app/views/plugins/email_tools/_form.slim
- config/locales/champaign.en.yml
* Added new postal variable to mail templates
* Adding ability to include variables both in the subjects and body.
I tried doing the same for EmailPension, but I found it's broken. The props are not being populated correctly, probably because of some issue with the Redux setup.
> Updated EmailTool templating and documentation

- app/views/layouts/member_facing.slim
- app/views/pages/_show.slim
- db/schema.rb
In order to run experiments that target specific templates, we need to be able to identify the template. This adds a meta tag with the template name, e.g.
```html
<meta name="liquid_layout" content="fundraiser with title below image" />
```
> Add a liquid_layout meta tag to page#show

- app/javascript/campaigner_facing/analytics.js
- app/views/api/analytics/show.json.jbuilder
- app/views/pages/_actions_analytics.slim
Removing it since this metric is not correct. Quoting Tara on this:
> the current stat shows the number of members that have never before taken an action on *Champaign*, which is different from the number of people who have never taken an action on *Action Kit*. Much of the difference comes from list swaps ... members that were imported directly into AK without going through Champaign, but there are other ways that people can get onto AK too ... like microsites
> Removing "New Members" metric from the analytics section

- app/liquid/views/partials/_form.liquid
Ther was some whitespace being inserted as a result of having the value on a new line and indented (in the template). This whitespace caused the default value to be picked up, and the placeholder to never show.
> Remove whitespace in textarea default values

- app/controllers/api/emails_controller.rb
- app/services/email_tool_sender.rb
In the past, AK required a postal code value (zip) for US based members. This requirement seems to have now been dropped. I've tested this change with various types of users from different locations, including the US.
> Removes hardwired postal code for call actions to ak

- app/javascript/components/MemberDetailsForm/MemberDetailsForm.js
- app/javascript/fundraiser/FundraiserView.js
- app/javascript/member-facing/backbone/action_form.js
- app/javascript/packs/fundraiser.js
- app/javascript/state/fundraiser/reducer.js
* Added `login_member` action to fundraiser store. This allows the member information to be set after the component has been initialized. 
* Modified `action_form.js` to publish the form data after being submitted. 
* Fixed bug that caused `action_form` to submit wrong values. The action form prefilling logic was broken, and was actually modifying the DOM in a wrong way (specifically checkboxes and radio buttons). The radio buttons, check boxes and textareas prefilling doesn't work (and wasn't working before either).
> Fundraiser login & ActionForm bug fix

- app/javascript/components/EmailEditor/EmailEditor.js
- app/javascript/email_tool/EmailToolView.js
One of the recent changes to `shouldComponentUpdate` to improve performance introduced this bug. We were only checking for changes in the Editor state, bug ignoring changes in the Subject, so the DOM element wasn't being updated with the text (it's a controlled element). This fixes it.
This also adds a `MAX_SUBJECT_LENGTH`, set to 64 characters.
> Fix EmailEditor subject field

- app/assets/stylesheets/campaigner-facing/page-edit.scss
- app/models/page.rb
- app/views/layouts/member_facing.slim
- app/views/pages/_form.slim
- config/locales/champaign.en.yml
- db/migrate/20180417152308_add_seo_fieldd_to_pages.rb
- db/schema.rb
- spec/models/page_spec.rb
- spec/requests/pages_spec.rb
For the `description` meta tag, if the field is left empty, then we use the default description that's in the locale file that we've been using.
> Added ability to set custom meta tags on any page

- spec/models/link_spec.rb
* The `link` was created outside the Timecop loop, making the updated_at possibly out of sync 
* Replaced `travel` by `freeze` making the code simpler. 
This is a screenshot of this spec failing on CircleCI
> Fixed spec that sporadically fails

- app/models/page.rb
- app/views/pages/_show.slim
Our previous `<meta name="optimization_tags" value="..." />` was fetched from a method called `meta_tags` on the page model. This was broken by a recent addition of actual meta tags to the page model. This PR brings the previous functionality back, but names it `optimization_tags` on the Page model.
> Fix missing optimization tags

- app/views/plugins/email_pensions/_form.slim
- app/views/plugins/email_tools/_form.slim
- app/views/plugins/shared/_subject_editor.slim
This stops chrome from replacing subject lines with autocomplete value for email.
> Define custom autocomplete values

- app/assets/stylesheets/campaigner-facing/page-edit.scss
- app/javascript/components/EmailEditor/EmailEditor.js
- app/javascript/components/EmailEditor/EmailEditor.scss
Removes extra `<br />` that was being inserted between header, body and footer. It also adds some CSS styles to ensure that there's a similar spacing in both the edit view (summernote) and the draft-js editor.
> Make spacing consistent in EmailEditor and raw email

- app/javascript/member-facing/backbone/petition_and_scroll_to_consent.js
This is to allow the Greenpeace template to work with the variant 3 of the consent flow. 
See: https://github.com/SumOfUs/sou-assets/pull/53
> Added callback option to PetitionAndScrollToConsent

- app/services/email_sender.rb
- spec/requests/api/emails_spec.rb
Simple format replaces `\n` with `<br>` adding extra new lines that makes the emails look funny. Like this one:
Can someone please test this on staging and deploy it tomorrow?
> Don't run simple_format on emails body

- app/javascript/packs/sentry.js
Sets the [user context](https://docs.sentry.io/learn/context/#capturing-the-user) in sentry when we know the user. Sets id, username, and ip address using `dataCallback` as described [here](https://docs.sentry.io/clients/node/config/).
> Set user context in sentry

- config/database.yml
- config/settings/production.yml
Currently using a default pool size of 5 connections per app instance. Our database can handle a great number more.
> Define db pool size via settings

- app/javascript/components/MemberDetailsForm/MemberDetailsForm.js
Added two small events to the fundraiser plugin form (member details). Simply emits a `fundraiser:form:success` event on successful validation, or a `fundraiser:form:error` with the response on failure.
> Introduce fundraiser:form:{success|error} events

- app/javascript/plugins/progress-tracker.js
The progress tracker header should have a transparent header, then transition to the teal background when the tracker is activated. This PR adds a `.with-progress-tracker` class to the header when the tracker is activated. Styles updated in the relevant `sou-assets` branch.
> Fix progress tracker styling

- app/controllers/api/payment/braintree_controller.rb
- app/controllers/concerns/exception_handler.rb
- app/lib/api/exceptions.rb
Ideally we should be using the plugin's form to validate the user, but at the moment this should suffice.
> Validate user in transaction payloads

- app/javascript/components/Payment/Payment.js
Generate new recaptcha token if the payment api returns an error. This allows the user to try the payment again without the need for refresh cc: @shivashankar-ror
> Generate new captcha token if payment api fails

- app/models/page.rb
- app/views/api/pages/index.json.jbuilder
- spec/models/page_spec.rb
- spec/requests/api/pages_spec.rb
Ticket:
https://app.asana.com/0/1119677445805032/1140485727078297
> Feature - added  percentage and action type attributes

- app/controllers/api/donations_controller.rb
- spec/controllers/api/donations_controller_spec.rb
This is needed for the EOY thermometer in mailings.
> Pass EOY goals for currencies hash in the api/donations/total endpoint

- .circleci/airbrake_register_deploy.sh
- .circleci/deploy.sh
- .circleci/deploy_testing.sh
- .prettierignore
- app/javascript/components/consent/ConsentControls.css
- app/javascript/legacy/member-facing/backbone/action_form.js
- config/settings/test.yml
- spec/controllers/api/go_cardless_controller_spec.rb
- spec/controllers/api/payment/braintree_controller_spec.rb
- spec/features/express_donations/email_one_click_spec.rb
- spec/features/express_donations/page_one_click_spec.rb
- spec/rails_helper.rb
- spec/requests/api/braintree/braintree_spec.rb
- spec/requests/api/braintree/failure_spec.rb
- spec/requests/api/braintree/webhook_spec.rb
- spec/requests/api/go_cardless/go_cardless_spec.rb
Backport a few other updates that have been rolled back from development:
* CSS updates to fix the sidebar look and feel.
* GDPR consent checkboxes are now appended to the form instead of in the button wrapper.
* Improve AWS labelling of artifacts:
```diff
- 3ebbaa02308cbdf6ab84d1653afdf5b3ce381d22
+ champaign-master-v3.0-1-3ebbaa023-config.zip
```
* Update deprecated syntax in rspec files.
> Raise errors for deprecations

- vendor/theme/templates/layouts/Default:-petition-and-scroll-to-share-greenpeace-refactor.liquid
It hasn't been thoroughly QA'd in comparison to the current state of the Greenpeace template - just moved over because at one point it was deleted from the `sou-assets` repository.
> Add greenpeace refactor template copied over from the feature environment

- app/controllers/api/payment/braintree_controller.rb
- app/services/payment_request_authorizer.rb
- spec/controllers/api/go_cardless_controller_spec.rb
- spec/controllers/api/payment/braintree_controller_spec.rb
- spec/features/express_donations/email_one_click_spec.rb
- spec/features/express_donations/page_one_click_spec.rb
- spec/requests/api/braintree/braintree_spec.rb
- spec/requests/api/braintree/failure_spec.rb
- spec/requests/api/braintree/webhook_spec.rb
- spec/requests/api/go_cardless/go_cardless_spec.rb
- spec/services/payment_request_authorizer_spec.rb
If Re-captcha score is less than 0.2, check whether the user have made at-least 2 donations already if so allow him to continue to the payment else block him.
> Allow users who have done 2 or more previous transactions to donate

- app/services/transaction_service.rb
In the TransactionService building the EOY translation amounts cache, manually exclude transactions that have nil for currency, as Currency.convert in app/lib/payment_processor/currency.rb will use 'USD' as the default currency if one is not passed, which inflates the donation amounts.
> Remove transactions that are not successful and that don't have a currency recorded from the EOY donations count

- app/javascript/components/Braintree/BraintreeCardFields.js
- app/javascript/components/Payment/Payment.js
- app/javascript/state/fundraiser/reducer.js
- package.json
- yarn.lock
* We have some reports about declined transactions due to 3D Secure authentication not being performed during checkout.
* For us to enable 3DS we needed to ask Braintree support to enable it for our merchant account (prod and sandbox) 
* For the **sandbox** account **we had to create a new one** since the one we're currently using is a marketplace account and 3DS is not supported for those types of accounts. 
* Upgraded `braintree-web` package version
* When creating the hosted fields in `createHostedFields` method, add the 3DS instance creation
* Added the instance to the state so it is available for us when needed.
* If for any reason the 3DS instance creation fails, the site should not break and the user should be able to continue with the donation as if 3DS was never enabled nor …
> Enable 3DS Support

- app/controllers/api/payment/braintree_controller.rb
I left the change unstaged; this should have been part of #1797 🤦🏼‍♀️
> Send merchantAccountId when generating bt token

- app/javascript/components/Payment/Payment.js
- app/lib/payment_processor/braintree/subscription.rb
- spec/lib/payment_processor/braintree/subscription_spec.rb
- spec/liquid/liquid_helper_spec.rb
- spec/requests/api/braintree/braintree_spec.rb
During the QA of 3DS, we encountered an error when trying to make a monthly donation. The error we are getting back from BT is:
````
Merchant account must match the 3D Secure authorization merchant account. (94284 on merchant_account_id)
````
The error happens when we call the `transaction` endpoint in Champaign; however, the issue is actually happening when we call the `create` method `::Braintree::PaymentMethod.create(payment_method_options)` because we are not sending the merchant account id information; therefore, Braintree uses the default.
The issue is affecting both, Champaign and Pronto.
https://app.asana.com/0/1119304937718815/1201335394700376/f
> Send Merchant Account Id to PaymentMethod Create

- app/lib/payment_processor/braintree/subscription.rb
- spec/lib/payment_processor/braintree/subscription_spec.rb
- spec/requests/api/braintree/braintree_spec.rb
When a subscription is created, we first call BT customer create method if the member is not already a customer; we need to send the merchant id for this call too; otherwise, we'll get a 3DS error regarding mismatching merchant account ids
> Send merchant account id for bt customer create

- app/views/api/pages/show.json.jbuilder
* Right now, the pages API does not include the donation bands in the response. This PR is adding that piece of data inside the fundraiser object so we can use it on pronto.
* The donation bands information is [inside the fundraiser plugin model](https://github.com/SumOfUs/Champaign/blob/development/app/models/plugins/fundraiser.rb#L52) on the `liquid_data` object
> Include Donation Bands On The Pages API

- app/admin/page.rb
- app/controllers/pages_controller.rb
- app/models/page.rb
- db/migrate/20220223114525_add_pronto_flag_to_page.rb
- db/schema.rb
- spec/controllers/pages_controller_spec.rb
- spec/factories/pages.rb
- spec/models/page_spec.rb
For routing traffic to pronto we're required to find suitable mailings where we can email a pronto url to half of the selected list. With this update we can have Champaign manage traffic to pronto directly. By setting the pronto flag to true (via the admin interface) on a particular page would redirect half of all traffic to pronto. NB: This PR isn't a solution for redirecting all petition traffic to pronto once we go live.
> pronto redirect

- app/assets/stylesheets/member-facing/petition.scss
- vendor/theme/stylesheets/components/photos.scss
* @edubsky  reported an issue where the campaign pages showed the sumofus logo and tagline right-aligned; this PR addresses that bug.
* The issue was a missing `html[dir=rtl]` selector on some CSS statements, therefore the RTL only CSS was applied to the LTR version of the page for the logo. 
**Before**
**After**
> Patch RTL style issue

- app/javascript/plugins/fundraiser/FundraiserView.js
I added a loading state on #1921, but if the members had some adBlockers installed, the extension would block google optimize script, and the loading state will remain falsy. 
With this PR, if the google optimize script is undefined (blocked), I set the loading state to true, and the donation bar should be shown to the end-user.
https://app.asana.com/0/1119304937718815/1202183747645773/f
Not all the ad blockers are blocking Google Optimize, the one with the problem right now is http://adblockultimate.net/
> Prevent page from not loading the donation bar if members had adBlocker installed

- app/controllers/liquid_layouts_controller.rb
- spec/controllers/liquid_layouts_controller_spec.rb
Only super admins can perform crud operations on templates; that work was done on #1924. However, it would be ok if not admin users still can see the list of available templates and not be able to edit them or add new templates.
> Follow up: Only super admin users can perform crud operations for liquid templates

- app/controllers/api/payment/braintree_controller.rb
- app/lib/payment_processor/braintree/one_click_from_uri.rb
- config/routes.rb
Endpoint takes the form:  `POST api/payment/braintree/pages/:page_id/express_payment`
The POST body takes the shape:
```json
{
"payment_method_ids": [
"kpw2r8b"
],
"currency": "GBP",
"amount": "1.50",
"allow_duplicate": true, # remove for production. This just allows you to test without getting throttled.
"user": {
"form_id": 75,
"name": "Some name",
"email": "test@example.com",
"postal": "xxxx",
"country": "ES"
},
"one_click": "true"
}
```
Mailing URLs for express donations will have the following query params: `amount`,  `currency`,  and `akid`.
> Provides new endpoint for express payments

- app/views/layouts/generic.slim
The [member authentication page was not being shown in Arabic](https://app.asana.com/0/1119304937718815/1202110539227254/f), instead fallbacks to default English
- I don't think this is a translation issue, since we already have translations for the content in our codebase.
- I tried on [an STG page](https://action-staging.sumofus.org/a/sample-petition-page), when I made a monthly donation with a new user the Member Auth page renders in Arabic. 
- The only issue which I noticed was the direction was not set as rtl. 
- I have fixed that in this PR.
[Loom Message - 5 May 2022 - Watch Video](https://www.loom.com/share/2f02abf7a0e54d13ac44fc50bada7782)
> Update direction of generic member facing pages to rtl when the lang is AR

- app/views/layouts/generic.slim
The [member authentication page was not being shown in Arabic](https://app.asana.com/0/1119304937718815/1202110539227254/f), instead fallbacks to default English
- I don't think this is a translation issue, since we already have translations for the content in our codebase.
- I tried on [an STG page](https://action-staging.sumofus.org/a/sample-petition-page), when I made a monthly donation with a new user the Member Auth page renders in Arabic. 
- The only issue which I noticed was the direction was not set as rtl. 
- I have fixed that in this PR.
[Loom Message - 5 May 2022 - Watch Video](https://www.loom.com/share/2f02abf7a0e54d13ac44fc50bada7782)
> Updates rendering direction of the page based on language

- app/controllers/api/payment/braintree_controller.rb
- app/controllers/pages_controller.rb
- app/lib/payment_processor/braintree/one_click.rb
- app/lib/payment_processor/braintree/one_click_from_uri.rb
* Error handling for the new express_payment API endpoint
* Handling invalid arguments as bad request response
* Handling BT customer not found as 404
* Handling every other error as an internal server error 
* Modified the success response
*  Included the follow-up URL
* Adding a `success` property
* Removed not needed information from the response
https://app.asana.com/0/1119304937718815/1201871673365341/f
```console
curl --location --request POST 'http://localhost:3000/api/payment/braintree/pages/10/express_payment' \
--header 'Content-Type: application/json' \
--data-raw '{
"one_click": true,
"payment_method_id":551,
"currency": "MXN",
"amount": "10",
"recurring_default": "one_off",
"user": {
"form_id": 166,
"name": "Yesi Molina",
"email": "yesi+33@sumofus.org",
"postal": "31160", …
```
> Error handling for one click api endpoint

- app/lib/payment_processor/braintree/one_click_from_uri.rb
The new one_click endpoint added on #1938 and refactored on #1945 is not working on one specific scenario for Pronto.
Adding logs will help me troubleshoot
> Adding logs to troubleshoot one_click endpoint

- .circleci/deploy.sh
- .ebextensions/02_container_commands.config
- app/lib/secrets_manager.rb
- config/initializers/application_secrets.rb
* Reverted the temp changes used to debug issues with deployment on staging:
* #1972
*  #1971
*  #1970
*  #1969
*  #1968
* Fixed an issue with Braintree and GoCardless discovered thanks to cypress on a pronto PR: https://github.com/SumOfUs/pronto/pull/145
* If we add setting values and then reload the settings if one nested object omits an existing property, it gets unset.
> Undo debugging changes for failed deployment

- app/views/pending_action_mailer/confirm_action.nl.html.erb
- app/views/pending_action_mailer/confirm_action.nl.text.slim
- app/views/pending_action_mailer/reminder.nl.html.slim
- app/views/pending_action_mailer/reminder.nl.text.slim
[Dutch petition can't be signed if the country field is "Duitsland" (Germany)](https://app.asana.com/0/1119304937718815/1202381186106512/f)
Champaign fails to submit a petition if I try to sign a petition with "Duitsland" selected from the "Land" country list.
- Initial observations revealed that it didn't happen for all the members, there was a specific pattern with the user's email address.
- When debugged further it was revealed that the confirm action email service was broken & it was causing the error
- Once an action is detected we will check if it's a Double OptIn country & if that's the case then a double optin email is triggered. Here the email template for the NL language was not available & has caused the issue. 
- Added the NL language templates for _confirm signature_ email & …
> Adds pending action emails for NL lang

- app/javascript/util/log_event.js
Noticed while doing QA on Champaign, that some of the new events for monthly sustainers were sending an array for label rather than the correct value.
Fixing this format error.
> Fixed data format on some of the events

- app/views/layouts/member_facing.slim
- app/views/shared/_ad_agency_pixel.slim
- app/views/shared/_tiktok_pixel.slim
- vendor/theme/templates/layouts/email-members-of-united-kingdom-parliament.liquid
To add new pixels for FB, Instagram & Tiktok for an Email MP campaign - [Email your MP: say no to a two-tier internet](https://actions.sumofus.org/a/email-your-mp-no-special-treatment-in-the-online-safety-bill/). This is for an external ad agency.
[Tracking pixel for email MP tool campaign](https://app.asana.com/0/1119304937718815/1202508133592193/f)
[Email your MP: say no to a two-tier internet](https://feature.sumofus.org/a/email-your-mp-no-special-treatment-in-the-online-safety-bill/)
Facebook Pixel
Tiktok Pixel
To remove the pixels once the experiment is completed
> Adds tracking pixels for FB, Instagram & tiktok for a specific campaign

- config/environments/production.rb
We are being throttled on staging and this is causing our cypress tests to fail.
Disabled throttling on staging to avoid issues with cypress.
When we enable cypress tests on production, we might need to do follow-up work on this.
In production, we don't want to disable the throttling, but we don't want to have it running on our own e2e tests, so we might need to implement some logic to make it work.
> Disable throttling on staging

- app/javascript/plugins/email_pension/EmailPensionView.js
- app/javascript/plugins/email_tool/EmailToolView.js
- app/services/unsafe_email_sender.rb
* Added the consent component to the email tool so the members can opt-in/out.
* Defaulted to false in case this same email sender is used somewhere else where we haven't added the consent UI yet 
https://app.asana.com/0/1119304937718815/1202585536107850/f
This PR needs to include `Plugin:EmailTool` as part of the following condition, so double opt-in works for the email tool too:
https://github.com/SumOfUs/Champaign/blob/development/app/services/manage_action.rb#L135
> Adding consent component to email tool

- app/controllers/api/emails_controller.rb
- app/javascript/plugins/email_pension/EmailPensionView.js
- app/javascript/plugins/email_pension/EmailRepresentativeView.js
- app/javascript/plugins/email_tool/EmailToolView.js
- app/javascript/plugins/email_tool/index.tsx
- app/javascript/util/ChampaignClient/Base.js
- app/javascript/util/ChampaignClient/MailerClient.js
Work involved:
The work at #2005 was meant to handle redirection to the follow-up page with the double-optin flag. However, when tested on STG, I found that the redirection didn't happen as expected. When debugged further the reason for that was we weren't making use of the JSON response from the API endpoint. I have fixed that in this PR.
Also for the EmailPension component, I have updated the code to send JSON response based on which the redirection happens
> Email tool redirections on double optin workflow

- app/liquid/champaign_liquid_filters.rb
- vendor/theme/templates/partials/_social_share_band.liquid
Follow-up PR for #2007 after I did QA on staging.
* Sometimes, JQuery is not loaded on the page on time, and the social menu is not loaded. To avoid this, I am using the load event from the document.
* Adding fallback click handlers in case share progress doesn't load or throws errors.
* Adding a helper method to load the assets from the asset path.
@subbiahf22  I am merging this, but please add any comment/feedback you have, and I'll address them on a separate PR.
> Adding fallbacks and not using jquery to avoid loading issues

- vendor/theme/templates/partials/_social_share_band.liquid
This  pull request is a follow-up from #2016 
Flora thought the copy functionality would include the copy of all the page content; however, that's a more extensive feature that's complex to develop due to the clipboard APIs, browser support, and image handling.
I suggested this patch; instead, which will provide extended functionality without increasing the complexity too much and thus extending the delivery date.
* The copy link button will copy the page title, the first paragraph of the main content, and the page link.
https://app.asana.com/0/1119304937718815/1202770241564374/f
The Clipboard API is not fully supported for all browsers; for example, Firefox does not support `ClipboardItem`
If the first paragraph happens to have an image, it can be supported by some browsers, but it …
> Modified the copy functionality to include title and first paragraph

- vendor/theme/templates/partials/_social_share_band.liquid
During QA, I noticed the link was showing after the title instead of the end.
This is only for the browsers that doesn't support the clipboard api
> Changed order to show link at the end

- app/controllers/pages_controller.rb
- app/models/page.rb
- config/application.rb
- lib/middleware/pronto.rb
- spec/controllers/pages_controller_spec.rb
- spec/models/page_spec.rb
* We want to set up a google Optimize experiment to redirect the supported fundraiser templates.
* Added the template to the `PRONTO_TEMPLATES` array
* Added new method to handle fundraiser experiment redirects
*  I could have used the same method, but then we will end up redirecting petition pages as part of the donations experiment.
* Extended tests
https://app.asana.com/0/1119304937718815/1202699940684642/f
@osahyoun @subbiahf22 We don't have a way to differentiate petitions vs. fundraisers with just the URL.
We need to either stop the petitions experiment and then run the fundraiser experiment or change the path for the fundraiser so we can set up the experiment on google optimize.
> Extend pronto supported templates for donations experiment

- app/views/api/pages/show.json.jbuilder
We need the `active` setting from the thermometer configuration to use it in pronto.
I have included all the settings and put them into their own `thermometer` node; I think it makes more sense and makes the JSON response cleaner.
https://app.asana.com/0/1119304937718815/1202883154800683/f
**Request**
```console
curl --location --request GET 'http://localhost:3000/api/pages/test-petition-123.json' 
```
**Response**
```json
{
"id": 13,
"title": "test petition 123",
"slug": "test-petition-123",
"content": "",
"created_at": "2022-04-06T20:54:49.715Z",
"updated_at": "2022-08-30T18:49:28.800Z",
"publish_status": "published",
"featured": false,
"action_count": 12,
"campaign_action_count": 12,
"meta_description": "",
"template_name": "Default: Petition And Scroll To Share Greenpeace", …
```
> Including all thermometer settings on the api response

- app/controllers/api/user_auth_controller.rb
- config/initializers/application_secrets.rb
- config/routes.rb
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
* We need a way to validate the session cookie created by champaign auth flow from pronto. To do that securely, I have added the following work to this PR:
* Using HTTP token authentication as `before_action` 
* For this, I added a `secretApiKey` into the secrets manager (one for dev and the other for production environments); this key needs to be present in the `Authorization` header from the pronto request. **This is our first secure filter**.
* Using the existing champaign authentication method to validate the user session (for this to work, we need to pass on the cookies from the pronto request).
* If either of the above secure checks fails, the endpoint will return a 401 response. 
https://app.asana.com/0/0/1202899413944404/f
**Authorized**
Request:
```console
curl --location …
```
> Adding user auth endpoint to be used by pronto

- app/javascript/plugins/email_tool/EmailToolView.js
- app/services/email_tool_sender.rb
This PR Fixes missing "consented" flag in Email Tool.
Due to this missing flag, the new Member's record was not created even when User consents to store their details in form of cookies.
> Email_Tool: Handling Consented Member's Cookies

- app/javascript/experiments/unintended-donations.js
- app/javascript/plugins/fundraiser/FundraiserView.js
The variant for the experiment is lower than the control for a little; however, we would like to test a small change:
* Instead of landing the members in step 1 any time we found an ID mismatch, we land them on step two if there is an amount selection
* This scenario is for when a member clicks on a specific amount on a fundraiser mailing.
* If there is no amount selection (member clicked on "Donate another amount" from the mailing), everything continues as is for variant 1, and we land the member on the first step. 
https://app.asana.com/0/1119304937718815/1202919967075456/f
https://user-images.githubusercontent.com/15176901/188754899-1c8764aa-e03d-4baf-ada0-cce2382dd31b.mp4
> Unintended donations experiment [PART 4]

- app/controllers/api/payment/braintree_controller.rb
We need to enable ReCaptcha again. However, pronto development is blocked, and all cypress donation specs fail.
Revert this PR once https://github.com/SumOfUs/pronto/pull/224 is merged
> Removing bot verification until pronto ReCaptcha is fixed

- app/liquid/liquid_renderer.rb
- app/models/page.rb
- app/views/api/pages/show.json.jbuilder
- app/views/pages/_follow_up_action_settings.slim
- app/views/pages/edit.slim
- config/locales/champaign.en.yml
- db/migrate/20220919211947_add_post_action_copy_and_image.rb
- db/schema.rb
- spec/factories/pages.rb
- spec/liquid/liquid_renderer_spec.rb
- spec/models/page_spec.rb
- spec/requests/api/pages_spec.rb
- vendor/theme/templates/layouts/post-donate-page-with-recurring-ask.liquid
* Added two new fields to the page model
* post_action_copy: If this field has value, then we will show it as the copy of the post donate page with recurring ask instead of the default copy.
* post_action_image_id: If an image is selected, it will replace the default image of the post donate page with a recurring ask page.
* Campaigners can modify these new fields on champaign edit page, and they will be visible only when the Post Donate Page With Recurring Ask template is selected as the follow-up action.
https://app.asana.com/0/1119304937718815/1202785217719163/f
https://user-images.githubusercontent.com/15176901/191337739-c1aa3474-a2ca-4ace-9916-1c8587a9c4a7.mp4
> Monthly Sustainers post donate page changes

- app/controllers/api/payment/braintree_controller.rb
* Our cypress e2e tests are failing on pronto due to the ReCaptcha verification we enabled last week. 
* With this PR, we are going to skip the ReCaptcha checks only when the Authorization header is present, and it is valid
* For this, we use basic HTTP auth with a bearer token, using the pronto API secret.  
https://app.asana.com/0/1119304937718815/1203056138127537/f
```console
curl --location --request POST 'http://localhost:3000/api/payment/braintree/pages/{id}/transaction' \
--header 'Content-Type: application/json' \
--header 'Cookie: _session_id=TheSessionId' \
--data-raw '{
"action_pronto": 1,
"amount": 1,
"currency": "USD",
"recurring": false,
"store_in_vault": false,
"user": {
"action_pronto": 1,
"name": "Yesi Molina",
"email": "yesi+aksakdsks@sumofus.org",
"postal": "31160", …
```
> Do not check ReCaptcha if the request is coming from cypress

- config/application.rb
* We will stop redirects to pronto temporarily while we regroup and perform a bug bash, fix all the outstanding issues and experiment again.
> Temporarily disabling pronto

- app/controllers/pages_controller.rb
* Removed the before action check to avoid adding the language to the url.
> Remove redirect to experiment

- Gemfile
- Gemfile.lock
- app/services/campaign_creator.rb
- app/services/event_bridge_service.rb
- spec/requests/campaigns_spec.rb
* The last piece of the serverless project's first milestone is creating campaigns without executing any code from the AK worker. This PR is that last piece.
* Added the event bridge service to put events on pulpo's bus.
* Replaced the champaign SQS push with the event bridge service call.
https://app.asana.com/0/1119304937718815/1202737927486106/f
>  Emit campaignCreated event from Champaign

- app/javascript/plugins/fundraiser/FundraiserView.js
* When the currency value on the query string parameters is invalid (cannot be mapped to our supported currencies), we default to USD. However, this can be problematic for our members since they expect to donate in their currency.
* When this scenario happens, we need to land our members on the first step of the fundraiser flow to let them change the currency.
https://app.asana.com/0/1119304937718815/1203048398756348/f
> Checking for invalid currency

- app/services/campaign_updater.rb
- spec/requests/campaigns_spec.rb
* Once a campaign is updated on Champaign, we need to emit an event to the pulpo event bus instead of pushing a message to the AK worker queue.
* This is to move towards a serverless, event-driven architecture.
* The event is listened to by a lambda function that will process it and then update the campaign on action kit.
https://app.asana.com/0/0/1203086766414494/f
> Publish campaignUpdatedOnChampaign event

- vendor/theme/templates/layouts/petition-with-large-image.liquid
- vendor/theme/templates/layouts/petition-without-image.liquid
- vendor/theme/templates/partials/_petition_with_small_image.liquid
* This is a patch for #2063. I discovered that some petition templates didn't have the fundraiser plugin. Therefore we cannot force a petition that has it on them because we will not have the information to render the page correctly.
* I added the fundraiser plugin to those templates as a hidden div, so if we don't force any template on them, the page will render correctly without showing the donation form (as it was first designed).
https://app.asana.com/0/1119304937718815/1203050335588363/f
> Added fundraiser plugin to templates

- app/services/campaign_creator.rb
- app/services/campaign_updater.rb
- spec/requests/campaigns_spec.rb
* I didn't notice an issue dependency between the pages and campaigns; when a campaign is created on Champaign, that campaign is now added to a dynamo table, and all subsequent updates are done in pulpo; that's great. However, this raises an issue when we assign a campaign to a page; since that is still happening on the worker, the campaign doesn't get assigned to the page (only on Champaigns DB but not on action Kit) because the campaign information does not exist on redis.
* The consequences of this could be that when the campaigners want to get all the action count for a campaign, they won't get the correct results of all the sum of the pages tied to a campaign.
* I updated the pages using pulpo's campaigns on AK (there were only 9 campaigns so far)
* Revert this PR once the next …
> Revert sending events to pulpo until pages services are done

- vendor/theme/templates/layouts/Default:-petition-and-scroll-to-donate-greenpeace.liquid
- vendor/theme/templates/layouts/Default:-petition-and-scroll-to-share-greenpeace.liquid
- vendor/theme/templates/layouts/end-of-year-scroll-to-share-2020.liquid
We're currently using the `CompleteRegistration` event on the FaceBook Ads manager to track conversions; however, that event can trigger more than once per action.
This PR will add a new event that only fires on successful action submissions.
> Adding new fb pixel event

- app/controllers/api/payment/braintree_controller.rb
- app/controllers/pages_controller.rb
- app/javascript/components/Payment/Payment.js
- app/lib/payment_processor/braintree/one_click.rb
- app/lib/payment_processor/exceptions.rb
- app/views/layouts/member_facing.slim
- app/views/pages/_personalization.slim
- app/views/shared/_champaign_object.slim
* If there is a failure on express donations (a member has saved payment methods and clicked on a one-click link from a fundraiser), we don't currently show any error message on the UI.
* This PR passes the error code back to the front end, where we can show a generic error message.
* The follow-up for this will be handling each error code independently to show better error messages for the members, however, there is a separate [task](https://app.asana.com/0/1119304937718815/1203423804221590/f) to do it, but we are waiting for translations. **This ticket will only show an error message on the UI**. 
* Return the error code on the express_donation and one_click endpoints, too, as pronto is using them, and we need to handle the errors there as well. 
* Improved the logging as we logged the …
> One click error handling

- app/javascript/components/Braintree/BraintreeCardFields.js
* Yasmin found an edge case while testing #2075. The issue happens when you try to donate with a 3DS verification and the donation fails for any reason, like canceling the 3ds verification, an expired card, or anything else. Then you try to resubmit the transaction (either changing anything on the form or not) in the second attempt; the 3DS iframe will show an error; however, on the third attempt, it will work.
* I researched, and it is because the teardown of the hosted fields was happening even though the transaction wasn't successful. This only happens when the 3DS verification is triggered.
* Moved the teardown call to the right place. 
https://user-images.githubusercontent.com/15176901/206266638-0cbe61d1-6984-4fbc-bc4e-8f9409348a89.mp4
> Patch 3ds blank popup after transaction error
