SumOfUs/Champaign

app/controllers/campaign_pages_controller.rb, app/views/campaign_pages/_form.slim, app/views/campaign_pages/edit.slim, app/views/campaign_pages/index.slim
A tiny branch and tiny PR to get started with featured pages (pages that are 'allowed' on the front page).
=> Featured pages

app/controllers/campaigns_controller.rb, app/models/campaign.rb, app/query_objects/active_query.rb, config/secrets.yml, spec/controllers/campaigns_controller_spec.rb, spec/models/campaign_spec.rb, spec/query_objects/active_query_spec.rb
Also, introduces `ActiveQuery` (query object).
=> Refactors campaigns controller, and adds some spec coverage.

spec/spec_helper.rb
https://github.com/SumOfUs/Champaign/blob/development/spec/rails_helper.rb#L61-L70
=> We're now using DatabaseCleaner

Gemfile.lock, app/config/champaign_config.rb, app/controllers/omniauth_callbacks_controller.rb, app/service_objects/connect_with_oauth_provider.rb, config/champaign.yml, config/locales/en.yml, spec/config/champaign_config_spec.rb, spec/fixtures/champaign.yml, spec/requests/omniauth_with_devise_spec.rb, spec/service_objects/connect_with_oauth_provider_spec.rb
=> Oauth whitelist

Gemfile.lock, app/assets/stylesheets/campaign_page.scss, app/assets/stylesheets/common.scss, app/controllers/campaign_pages_controller.rb, app/views/campaign_pages/index.slim, config/locales/en.yml, spec/controllers/campaign_pages_controller_spec.rb
See issue https://github.com/SumOfUs/Champaign/issues/54
=> Takes a step back on the campaign_pages#index

app/assets/javascripts/components/edit_campaign_page.js.jsx, app/assets/javascripts/components/widgets_box.js.jsx
I felt like this react branch with the controller changes was blocking me doing useful work on controller specs, so I decided to try getting my hands dirty with React. it took a while to wrap my head around it, but I think I got the hang of it and was able to make a usable contribution. 
When I first tried to load the edit page that uses the react components, I was confronted by a swath of javascript errors and react warnings. These changes deal with all of the errors and most of the warnings. It also creates infrastructure to edit other types of widgets, and it gets the edit toggle button to switch between the show and the edit views.
@osahyoun these were originally going to be commits directly to your `react` branch, but I wasn't sure if that would step on your toes so I thought it best …
=> React merge asap

app/controllers/campaign_pages_controller.rb
Pretty simple, useful for routing on the processor end.
=> Add call type to SQS calls

app/controllers/campaign_pages_controller.rb, app/liquid/liquid_file_system.rb, app/models/campaign_page.rb, app/models/liquid_layout.rb, app/models/plugins/action.rb, app/views/plugins/actions/_action.liquid, app/views/plugins/partials/_photos.liquid, app/views/plugins/templates/main.liquid, app/views/plugins/thermometers/_thermometer.liquid
When this PR is done, Champaign will check database first for partial/template. When not found, it'll search the filesystem.
=> Adds partials to filesystem

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/liquid/syntax-highlighting.js, app/assets/stylesheets/application.scss, app/views/liquid_layouts/_form.html.slim, app/views/liquid_partials/_form.html.slim
=> add html syntax highlighting to liquid editors

app/assets/stylesheets/common.scss, app/controllers/api/actions_controller.rb, app/models/action.rb, app/models/plugins/action.rb, app/views/campaign_pages/edit.slim, app/views/plugins/actions/_action.liquid, config/locales/en.yml, db/migrate/20150813140155_add_form_data_to_actions.rb, db/schema.rb, spec/controllers/api/actions_controller_spec.rb
=> Action update

spec/lib/champaign_queue/clients/sqs_spec.rb
@Tuuleh this should sort our the bug
=> Bullet proof spec.

app/assets/javascripts/forms.js, app/views/forms/edit.html.slim
@NealJMD thank you for fixing `sortable` on `forms/edit`! I'm just adding the pub/sub behaviour back in, if that's ok.
=> Use pub/sub so javascript is only executed on relevant view.

app/assets/javascripts/forms.js, app/views/plugins/actions/_form.slim
Form management was broken after last merge.
=> Publishes event so that forms are editable again.

app/assets/javascripts/show_errors.js
Not fully supported, yet.
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings
=> Removes ES6 interpolation.

Dockerfile, Gemfile, Gemfile.lock, config/newrelic.yml, docker-compose.yml
Gets us a production-capable web server and NewRelic integration for stats tracking. 
For reasons I can’t explain, modifying the last line of the docker file isn’t changing the command that’s run on docker-compose up (I’m still getting WEBrick but expecting Unicorn). Am I misremembering the file to modify?
=> Adding NewRelic and Unicorn

Gemfile, Gemfile.lock, config/env.yml.template, config/environments/production.rb
For hosting and serving our compressed assets on `S3`. Assets will be pushed after `assets:precompile`.
=> Upload assets to s3

app/assets/stylesheets/sumofus/components/campaigner-overlay.scss, app/views/layouts/sumofus.slim
Allows users to open the edit page form from the page preview.
=> Adding edit link for logged in users to layout page.

.ebextensions/03_container_commands.config, circle.yml
Does two things:
1. adds an env var to static assets script so it knows to send them to S3 after precompiling them
2. adds a script to remove non-running containers and old images between deploys to prevent the environment running out of disk space
=> Add Docker housekeeping

app/controllers/ak_logs_controller.rb, app/models/ak_log.rb, app/views/ak_logs/index.html.slim, app/views/ak_logs/show.html.slim, config/locales/en.yml, config/routes.rb, db/migrate/20150930130924_create_ak_logs.rb, db/schema.rb, spec/controllers/ak_logs_controller_spec.rb, spec/factories/ak_logs.rb, spec/models/ak_log_spec.rb
I'm going to merge this once it's green, so I can see it on staging. I'll formalise the PR afterward.
=> AKLog for ActionKit communications.

app/assets/stylesheets/sumofus/components/button.scss, app/assets/stylesheets/sumofus/components/footer.scss, app/assets/stylesheets/sumofus/components/form.scss, app/assets/stylesheets/sumofus/components/header.scss, app/assets/stylesheets/sumofus/components/petition.scss, app/assets/stylesheets/sumofus/global/layout.scss, app/assets/stylesheets/sumofus/pages/share.scss, app/controllers/pages_controller.rb, app/models/image.rb
After using browser stack to check things out in a bunch of different browsers, I made these changes that address all the little bugs I could find.
=> Style tweaks

Gemfile, Gemfile.lock
so we can move faster, and so right now we can get request logging
=> use share_progress gem from Git

app/assets/stylesheets/sumofus/components/photos.scss, app/liquid/views/layouts/sumofus.liquid, app/views/plugins/actions/_preview.html.slim
This just takes care of some little stuff - centers the cover photo, links the header to sumofus.org, and shows the petition target in the action form preview.
=> Layout tweaks

app/controllers/pages_controller.rb
I'm not sure how this commit got lost, I think I might never have pushed it. I had it on Eric's branch, but it needs to get merged more urgently anyway.
=> protect against 500 when geocoder location times out

app/views/pages/_shares_editor.slim, app/views/pages/edit.slim, config/locales/en.yml
=> Add tbody to table

config/environments/production.rb
=> Unify buckets

app/services/manage_action.rb, circle/test.env, spec/factories/forms.rb, spec/requests/api/actions_spec.rb, spec/services/manage_action_spec.rb
+ Adds request spec coverage for creating an action.
+ Wraps main params in body
Necessary PR for stuff I'm doing on ak-processor
=> Request spec plus format change to params body

Gemfile, Gemfile.lock, config/initializers/sentry.rb
We should get notified when stuff explodes (email and slack). I've used sentry before. They have a free tier. Let me know if you see a problem in using this particular service.
=> Load and initialise 'Sentry'

app/models/action_user.rb, app/services/manage_action.rb, spec/services/manage_action_spec.rb
Deal with some last stuff Omar brought up as we were merging the recognize user stuff.
=> Recognize cleanup

app/controllers/api/braintree_controller.rb, app/models/page.rb, app/models/payment.rb, app/models/payment/braintree_customer.rb, app/models/payment/braintree_transaction.rb, circle/test.env, config/environments/test.rb, db/migrate/20151117154619_create_payment_braintree_transactions.rb, db/migrate/20151118132544_create_payment_braintree_customers.rb, db/schema.rb, lib/payment_processor/clients/braintree/transaction.rb, spec/controllers/api/braintree_controller_spec.rb, spec/factories/payment_braintree_customers.rb, spec/factories/payment_braintree_transactions.rb, spec/fixtures/vcr_cassettes/repeat_transaction_success.yml, spec/fixtures/vcr_cassettes/transaction_success.yml, spec/models/payment/braintree_customer_spec.rb, spec/models/payment/braintree_transaction_spec.rb, spec/models/payment_spec.rb, spec/requests/api/braintree_spec.rb
@NealJMD  it's WIP, but want this PR open early incase it touches on what you're doing.
=> Braintree store

app/admin/donation_band.rb, app/controllers/donation_bands_controller.rb, app/models/donation_band.rb, app/views/donation_bands/_form.slim, app/views/donation_bands/edit.slim, app/views/donation_bands/index.slim, app/views/donation_bands/new.slim, app/views/donation_bands/show.slim, app/views/plugins/fundraisers/_form.slim, app/views/shared/_navbar_links.slim, config/locales/en.yml, config/routes.rb, db/migrate/20151130211806_add_donation_band_id_to_fundraisers.rb, lib/donation_band_converter.rb, spec/controllers/donation_bands_controller_spec.rb, spec/lib/donation_band_converter_spec.rb
This adds a UI for creating/editing/viewing donation bands, and adds the UI for a fundraiser to accept a default donation band, which will be displayed when the page shows up.
=> Donation Bands

app/assets/javascripts/sumofus/backbone/currency_methods.js, app/assets/javascripts/sumofus/backbone/fundraiser_bar.js, app/assets/stylesheets/sumofus/components/fundraiser.scss, app/views/plugins/fundraisers/_fundraiser.liquid, spec/javascripts/member-ui/fundraiser_spec.js
This PR adds the UI to switch between currencies on the fundraiser bar, including JS tests.
=> Switch currency

app/services/manage_donation.rb, spec/services/manage_donation_spec.rb
Setting up for finishing off AK integrations on donations.
=> Adding ManageDonation class to allow for pushing donation events to the queue like Actions.

app/assets/javascripts/sumofus/backbone/hosted_fields.js, app/assets/stylesheets/sumofus/components/fundraiser.scss, app/assets/stylesheets/sumofus/global/colors.scss, app/views/plugins/fundraisers/_fundraiser.liquid
It pretty much just drops right in. It's still a little unclear if it works with foreign currencies, but this PR is just for the front-end.
=> Add Paypal to donations UI

app/controllers/api/braintree_controller.rb, app/models/member.rb, app/models/payment.rb, app/models/payment/braintree_customer.rb, db/migrate/20151211172648_add_member_fk_to_braintree_customers.rb, db/migrate/20151214155329_add_payment_instrument_type_to_payment_braintree_transactions.rb, db/schema.rb, lib/payment_processor/clients/braintree/subscription.rb, spec/controllers/api/braintree_controller_spec.rb, spec/fixtures/vcr_cassettes/transaction_paypal_success.yml, spec/lib/payment_processor/clients/braintree/subscription_spec.rb, spec/models/payment/braintree_customer_spec.rb, spec/models/payment_spec.rb, spec/requests/api/braintree_spec.rb
I'm finding `customer`, `@customer` and `customer_details` in `payment.rb` really confusing.
```
(byebug) customer_details
#<Braintree::Transaction::CustomerDetails:0x007f157ff34580>
(byebug) customer
#<Braintree::Transaction::CustomerDetails:0x007f157ff34580>
(byebug) @customer
#<Braintree::Transaction::CustomerDetails:0x007f157ff34580>
```
In Payment#BraintreeTransactionBuilder#build, I'm unclear on the purpose of `unless customer`. As far as I can see, the condition hits every time, because `customer` is either `customer_attributes`, or whatever is found with `Payment.customer(customer_details.email)`. So since that condition seems to pass every time, a new braintree customer gets created every time, and it can be identical to an existing customer. Could you have a look and verify? 
I …
=> Associate member with customer

app/models/plugins/thermometer.rb, spec/models/plugins/thermometer_spec.rb
Handles [this pivotal ticket](https://www.pivotaltracker.com/n/projects/1364614/stories/110081516) to make the thermometer start at 100 and increment by 100 until it reaches 500. This guy should be ready to merge!
=> Start thermometer at 100

app/controllers/api/braintree_controller.rb, app/models/payment.rb, spec/controllers/api/braintree_controller_spec.rb, spec/fixtures/vcr_cassettes/braintree_subscription_success.yml, spec/fixtures/vcr_cassettes/transaction_recurring_success.yml, spec/models/payment_spec.rb, spec/requests/api/braintree_spec.rb
@Tuuleh stab at updating `Payment.customer` to find customer from it's associated member, thus allowing us to remove `email` from the customer's attributes. Some failing specs still to be fixed, but popping out for a late lunch.
=> Find customer from member

Gemfile, Gemfile.lock, config/initializers/sentry.rb, config/settings.yml, config/settings/production.yml
Not really required, now that we have papertrailapp.
=> Drops sentry.

app/assets/javascripts/sumofus/backbone/hosted_fields.js, app/assets/stylesheets/sumofus/components/fundraiser.scss, app/views/plugins/fundraisers/_fundraiser.liquid, spec/javascripts/member-ui/fundraiser_spec.js
This PR makes it so that when a user authorizes through Paypal, it hides the credit card fields, and when a user enters a credit card it grays out the Paypal button.
=> Payment focus

app/assets/javascripts/page.js, app/assets/stylesheets/page-edit.scss, app/views/pages/_collapsing_layout_select.slim, app/views/pages/_layout_select.slim, app/views/pages/_settings_form.slim, app/views/pages/new.slim, config/locales/champaign.en.yml
commit messages pretty much say it all
=> Minor tweaks

app/assets/images/sumofus/corner.svg, app/assets/javascripts/sumofus/backbone/fundraiser_bar.js, app/assets/javascripts/sumofus/backbone/petition_bar.js, app/assets/stylesheets/sumofus/components/fundraiser.scss, app/assets/stylesheets/sumofus/components/petition.scss, app/assets/stylesheets/sumofus/global/colors.scss, app/assets/stylesheets/sumofus/global/layout.scss, app/liquid/views/layouts/standard-fundraiser.liquid, app/liquid/views/layouts/standard-petition.liquid, app/views/plugins/fundraisers/_fundraiser.liquid, app/views/plugins/petitions/_petition.liquid
The way that the original designs hid the petition ask was widely reviled by campaigners, so we went back to Rohan to get a new treatment. This implements one of the available options (the one I liked the best) leaving open the possibility of testing alternatives with Optimizely down the line.
=> Petition ask redesign

.ebextensions/02_container_commands.config
=> Set ENV for redis server

app/controllers/plugins/forms_controller.rb, app/models/form.rb, app/models/plugins/has_form.rb, spec/models/form_element_spec.rb, spec/models/form_spec.rb, spec/models/plugins/shared_examples.rb
Delete existing form.
Validate uniqueness for formable_id
=> API method for updating plugins form.

README.md
=> Mention browserstack in readme for free account

app/services/manage_braintree_donation.rb, spec/requests/api/braintree_spec.rb, spec/services/manage_braintree_donation_spec.rb
=> Build and pass payment_account

config/locales/sumofus.de.yml
=> Shortened the 'change user' link to "Nicht Sie?"

app/services/manage_action.rb, spec/requests/api/actions_spec.rb, spec/services/manage_action_spec.rb
Request made with a valid referring akid:
=> Pass referring akid to ActionKit, where it'll be processed if valid

app/assets/javascripts/sumofus/backbone/form_methods.js, app/assets/javascripts/sumofus/backbone/fundraiser_bar.js, app/assets/javascripts/sumofus/backbone/hosted_fields.js, app/assets/javascripts/sumofus/backbone/petition_bar.js, app/assets/stylesheets/sumofus/components/footer.scss, app/assets/stylesheets/sumofus/components/petition.scss, app/assets/stylesheets/sumofus/global/layout.scss, app/assets/stylesheets/sumofus/global/mixins.scss, app/assets/stylesheets/sumofus/global/typography.scss, app/liquid/views/layouts/fundraiser-with-large-image.liquid, app/liquid/views/layouts/fundraiser-with-small-image.liquid, app/liquid/views/layouts/petition-with-large-image.liquid, app/liquid/views/layouts/petition-with-small-image.liquid, app/liquid/views/partials/_fundraiser_mobile_footer.liquid, app/liquid/views/partials/_petition_mobile_footer.liquid, app/liquid/views/partials/_small_image_footer.liquid, app/views/plugins/fundraisers/_form.slim, app/views/plugins/fundraisers/_fundraiser.liquid, app/views/plugins/petitions/_petition.liquid, config/locales/champaign.en.yml, config/locales/sumofus.de.yml, config/locales/sumofus.en.yml, config/locales/sumofus.fr.yml
deals with a number of visual bugs
- the form could get cut off at the end of the page, but it now scrolls when overflowing
- the action button was getting covered by the footer at the bottom of the page
- the action button stuttered when scrolling
- the credit card validation errors in french and german were grammatically incorrect
=> [Pre-deploy] CSS QA

app/assets/javascripts/layout_picker.js, app/assets/javascripts/tooltips.js, app/liquid/views/layouts/post-donation-share.liquid, app/liquid/views/layouts/post-petition-share.liquid, app/liquid/views/partials/_share_page.liquid, app/views/pages/new.slim, config/locales/sumofus.de.yml, config/locales/sumofus.en.yml, config/locales/sumofus.fr.yml
=> Copy fixes

app/services/action_queue.rb, lib/user_language_iso.rb, spec/factories/languages.rb, spec/lib/user_language_iso_spec.rb, spec/requests/api/braintree_spec.rb, spec/requests/api/braintree_webhook_spec.rb
Pass language iso to AK with action.
https://www.pivotaltracker.com/story/show/113874887
=> Language ISO in user params

app/assets/stylesheets/page-edit.scss, app/views/layouts/application.html.slim
Paul said it was requested twice in hallway tests so he made a ticket and I did it.
=> Make nav header position: fixed on campaigner ui

app/controllers/share/shares_controller.rb, spec/controllers/share/shared_examples.rb
https://www.pivotaltracker.com/story/show/115036273
=> Updates SP URL

app/services/queue_manager.rb, config/settings/production.yml, config/settings/test.yml, spec/services/queue_manager_spec.rb
https://www.pivotaltracker.com/story/show/115268963
=> Pass page url and hosting platform ID

app/services/action_queue.rb, config/initializers/countries.rb, spec/requests/api/actions_spec.rb, spec/services/manage_braintree_donation_spec.rb
Eric, learnt from Simona this morning that there are more countries for the list! This PR adds the new names and pushes the changes to the countries lib.
=> Adds additional countries to exceptions list

db/seeds.rb, spec/support/helper_functions.rb
Three campaigner tags were missing. Also deleting language tags as not needed given pages have a language (in consultation with Tara/Simona).
Tell me what I did wrong! Something I'm sure, even though this is super simple.
=> Updating tags by removing languages, adding campaigners

config/locales/champaign.en.yml
Teeny tooltip change to resolve a confusion with thermometer offset field.
=> Tiny change to thermometer tooltip

config/locales/champaign.en.yml
Just to address a ticket re field names that is sitting in current but that Neal missed.
=> Quick update to forms tooltip

app/views/pages/_share_analytics_header.slim, app/views/pages/_shares_editor.slim, app/views/pages/analytics.slim, app/views/share/_stats_row.slim, app/views/share/emails/_email.html.slim, app/views/share/facebooks/_facebook.html.slim, app/views/share/twitters/_twitter.html.slim
Today Liz requested that we show the sharing stats on the analytics page. It was mostly a matter of shuffling around some partials, so I went ahead and did it.
=> Show share stats on analytics page

app/assets/javascripts/sumofus/backbone/petition_bar.js
The form sizing stuff was making things wonky on mobile. See [this ticket](https://www.pivotaltracker.com/story/show/116768783)
=> don't do tricky form sizing stuff on mobile

app/models/payment.rb, app/models/payment/braintree_customer.rb, app/models/payment/braintree_payment_method.rb, app/models/payment/braintree_transaction.rb, db/migrate/20160314215202_multiple_payment_method_tokens.rb, db/migrate/20160314221437_rename_card_vault_token.rb, db/migrate/20160318231720_make_transaction_payment_method_token_foreign_key.rb, db/migrate/20160322224507_make_foreign_key_columns_integers.rb, db/migrate/20160331210529_rename_tokens_to_payment_methods.rb, db/schema.rb, lib/payment_processor/clients/braintree/webhook_handler.rb, spec/factories/payment_braintree_customers.rb, spec/fixtures/vcr_cassettes/transaction_existing_customer_storing_multiple_tokens.yml, spec/models/payment_spec.rb, spec/requests/api/braintree_spec.rb
=> omar's tinkering

spec/fixtures/vcr_cassettes/gocardless_successful_transaction.yml, spec/requests/api/gocardless/gocardless_spec.rb
This PR gives us a path forward for creating integration specs for GoCardless. Once these tests are filled out and passing, we'll be done except for webhooks and the failure case.
feel free to comment but just merge it cause `going-cardless` is WIP anyway
=> Cardless specs

spec/fixtures/vcr_cassettes/gocardless_redirect_flow_post_back_payment.yml, spec/fixtures/vcr_cassettes/gocardless_successful_transaction.yml, spec/requests/api/gocardless/gocardless_spec.rb
I've now finished implementing the success case specs. The spec will need some tweaks, but it's already worth running as you implement stuff.
=> implement the integration spec for GoCardless

app/controllers/payment_controller.rb, app/models/payment/go_cardless.rb, lib/payment_processor/go_cardless/subscription.rb, lib/payment_processor/go_cardless/transaction.rb, spec/controllers/api/go_cardless_controller_spec.rb, spec/controllers/api/payment/braintree_controller_spec.rb, spec/lib/payment_processor/clients/braintree/transaction_spec.rb, spec/lib/payment_processor/go_cardless/subscription_spec.rb, spec/lib/payment_processor/go_cardless/transaction_and_subscription_examples.rb, spec/lib/payment_processor/go_cardless/transaction_spec.rb
Nothing too complicated tested here, but I thought it would be good to throw a unit test on these.
=> GC unit specs

app/models/payment/go_cardless/subscription.rb, lib/payment_processor/clients/braintree/webhook_handler.rb, spec/lib/payment_processor/clients/braintree/webhook_handler_spec.rb, spec/lib/payment_processor/go_cardless/webhook_handler_spec.rb
ActionKit have improved their API.
=> Post original payment to AK

app/models/payment.rb, lib/payment_processor/clients/braintree/subscription.rb, lib/payment_processor/clients/braintree/webhook_handler.rb, spec/lib/payment_processor/clients/braintree/subscription_spec.rb, spec/lib/payment_processor/clients/braintree/webhook_handler_spec.rb, spec/requests/api/braintree_spec.rb, spec/requests/api/braintree_webhook_spec.rb
surprised this was still happening.
=> Rely on webhook for transaction generation

app/liquid/views/partials/_full_width_header.liquid, app/liquid/views/partials/_share_page.liquid, app/liquid/views/partials/_simple_footer.liquid, app/liquid/views/partials/_small_header.liquid, app/liquid/views/partials/_small_image_footer.liquid, config/locales/sumofus.de.yml, config/locales/sumofus.en.yml, config/locales/sumofus.fr.yml
We have fr.sumofus.org and de.sumofus.org for French and German petition and donate page footer links to link to.
=> Localise footer links

app/models/user.rb
easier than I thought it would be.
=> Don't make user registerable

app/models/payment/go_cardless.rb, app/services/action_queue.rb, lib/payment_processor/go_cardless/populator.rb, lib/payment_processor/go_cardless/subscription.rb, lib/payment_processor/go_cardless/transaction.rb, spec/fixtures/vcr_cassettes/go_cardless_successful_subscription.yml, spec/fixtures/vcr_cassettes/go_cardless_successful_transaction.yml, spec/lib/payment_processor/go_cardless/subscription_spec.rb, spec/lib/payment_processor/go_cardless/transaction_spec.rb, spec/requests/api/go_cardless/go_cardless_spec.rb
For the confirmation emails, we need bank name and the end of the bank account number. This PR makes us pass that through to AK.
=> pass bank name and end of account number from GC to AK

app/assets/stylesheets/sumofus/pages/page.scss, app/controllers/api/pages_controller.rb, app/models/page.rb, config/routes.rb, spec/controllers/api/pages_controller_spec.rb, spec/models/page_spec.rb, spec/requests/api/pages_spec.rb
- was adding this CSS fix for margins when I realized page updating was broken
- fixed it in a different way than in omar's other PR (I think its snazzier)
- but still no tests. that's totally my bad - I don't know how I never wrote a test for one of the most critical routes we have
- also refactored a little bit in the controller because I found `show_single_page` a bit confusing
=> Pages controller fix

spec/controllers/application_controller_spec.rb, spec/controllers/pages_controller_spec.rb, spec/liquid/liquid_i18n_spec.rb, spec/liquid/liquid_renderer_spec.rb, spec/requests/localization_spec.rb, spec/spec_helper.rb
Trying to end the random i18n failures, because locale isn't being reset.
=> Reset locale from spec helper

app/controllers/campaigns_controller.rb, app/services/campaign_creator.rb, app/services/campaign_updater.rb, config/locales/champaign.en.yml, spec/controllers/campaigns_controller_spec.rb, spec/requests/campaigns_spec.rb
TODOS:
* Publish event (and process it on ak_processor) when a campaign is updated
* Add campaign_id to page#create and page#update events.
=> Publish event after creating a Campaign

Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/routes.rb, spec/requests/api/cors_spec.rb, spec/support/request_helpers.rb
=> Enable CORS in /api namespace

app/services/queue_manager.rb, spec/services/queue_manager_spec.rb
First merge this PR: https://github.com/SumOfUs/champaign-ak-processor/pull/72/files
=> Add campaign id param when publishing page events

app/assets/stylesheets/sumofus/pages/baysanto.scss, app/controllers/uris_controller.rb, app/liquid/views/partials/_baysanto.liquid, app/views/plugins/petitions/_petition.liquid, config/locales/sumofus.de.yml, config/locales/sumofus.en.yml
Don't release to prod without these (these layout changes are reflected already in the db and if you deploy without this you'll overwrite them)
=> Baysanto cleanup

app/services/manage_action.rb, db/migrate/20160802225329_add_allow_duplicate_actions_to_page.rb, db/schema.rb, spec/requests/api/actions_spec.rb, spec/services/manage_action_spec.rb
This flag will allow a member to create multiple actions against the same page.
=> Set flag to allow multiple actions per page

app/models/plugins/thermometer.rb
This removes the Enumerator which is used for dynamic goal calculation and replaces it with a more mathematical solution.
=> Thermometer

Gemfile, Gemfile.lock, config/initializers/actionkit_connector.rb, config/settings/development.yml, db/seeds.rb, lib/tasks/action_kit.rake
Need to merge merge this other PR before merging this one: https://github.com/SumOfUs/actionkit_connector/pull/8
=> Remove custom data from seeds

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/member-facing/backbone/action_form.js, app/assets/javascripts/member-facing/backbone/fundraiser.js, app/assets/javascripts/member-facing/backbone/payment-methods/payment-method.view.js, app/assets/javascripts/member-facing/backbone/payment-methods/payment-methods.view.js, app/liquid/liquid_renderer.rb, app/liquid/views/partials/_oneclick_form.liquid, app/views/plugins/fundraisers/_fundraiser.liquid, package.json, spec/liquid/liquid_renderer_spec.rb
The fundraiser sidebar now renders payment methods in the browser.
Also closes [#130729103](https://www.pivotaltracker.com/story/show/130729103) and [#130627265](https://www.pivotaltracker.com/story/show/130627265).
=> Refactor payment methods view

app/assets/javascripts/member-facing.js.erb, app/assets/javascripts/member-facing/backbone/notification.js, app/controllers/member_authentications_controller.rb, app/views/layouts/_notification.slim, app/views/layouts/member_facing.slim, spec/controllers/member_authentications_controller_spec.rb, spec/mailers/confirmation_mailer_spec.rb
Adds a flash partial to the member facing layout and sets a flash notice after a member registers.
=> Pass flash notification after registering.

app/assets/javascripts/member-facing/backbone/payment-methods/payment-methods.view.js, app/assets/stylesheets/member-facing/form.scss, app/assets/stylesheets/member-facing/fundraiser.scss, app/assets/stylesheets/member-facing/petition.scss, app/assets/stylesheets/member-facing/registration.scss, app/liquid/views/partials/_oneclick_form.liquid, config/locales/member_facing.de.yml, config/locales/member_facing.en.yml, config/locales/member_facing.fr.yml
Tweaking the visuals of the new one-click flows for aesthetics and clarity.
=> One click polish

app/models/action.rb, app/services/action_builder.rb, lib/payment_processor/braintree/one_click.rb, spec/fixtures/vcr_cassettes/braintree_multiple_transactions.yml, spec/fixtures/vcr_cassettes/express_donation_multiple_transactions.yml, spec/models/action_spec.rb, spec/requests/api/braintree/braintree_spec.rb
For this ticket: https://www.pivotaltracker.com/n/projects/1364614/stories/131986701
=> Enable creating multiple actions and transactions through express donations, and create actions only if transactions are successful.

config/locales/member_facing.en.yml
In line with Optimizely testing results
=> Tweak express copy

Gemfile, Gemfile.lock, config/initializers/airbrake.rb, config/settings/production.yml
:taco:
Airbrake creds already set on staging
=> Installed Airbrake

app/controllers/api/stateless/auth_controller.rb, app/controllers/email_confirmation_controller.rb, app/models/member.rb, app/models/payment/braintree.rb, app/services/action_builder.rb, app/services/braintree_services/payment_options.rb, app/services/email_verifier_service.rb, app/services/manage_donation.rb, app/services/member_with_authentication.rb, spec/lib/payment_processor/braintree/subscription_spec.rb, spec/lib/payment_processor/braintree/transaction_spec.rb, spec/models/member_spec.rb
We're fetching member by email in  multiple places (without calling `downcase` on the address).
=> Introduce a single method for find member by email

app/assets/javascripts/campaigner-facing/configure_wysiwyg.js, app/controllers/plugins/texts_controller.rb, app/helpers/pages_helper.rb, app/models/plugins.rb, app/models/plugins/text.rb, app/views/pages/_form.slim, app/views/pages/edit.slim, app/views/plugins/texts/_form.slim, app/views/plugins/texts/_text.liquid, app/views/shared/_wysiwyg.slim, config/routes.rb, db/migrate/20161028200018_create_text_plugin.rb, db/schema.rb, spec/factories/plugins_text.rb, spec/models/plugins/text.rb
This is a really simple plugin, but one that I think will make a lot of stuff I do for microsites much easier. There's a forthcoming PR on sou-assets where I use it on a new generalized version of it for the action-center page.
=> Create new Text plugin type

app/controllers/member_authentications_controller.rb, app/services/page_follower.rb, spec/controllers/member_authentications_controller_spec.rb
[Delivers #131809049](https://www.pivotaltracker.com/story/show/131809049)
=> Correctly generate followup path after member registers

app/assets/javascripts/campaigner-facing/form_element_creator.js, app/assets/javascripts/member-facing.js.erb, app/assets/javascripts/member-facing/backbone/action_form.js, app/assets/javascripts/member-facing/backbone/survey.js, app/assets/javascripts/member-facing/backbone/sweet_placeholder.js, app/assets/stylesheets/member-facing/form.scss, app/assets/stylesheets/member-facing/fundraiser.scss, app/assets/stylesheets/member-facing/survey.scss, app/controllers/form_elements_controller.rb, app/liquid/views/partials/_form.liquid, app/liquid/views/partials/_generic_form.liquid, app/liquid/views/partials/_survey_form.liquid, app/models/form_element.rb, app/models/plugins/has_form.rb, app/services/form_element_builder.rb, app/views/forms/_add_element.slim, app/views/forms/_preview.html.slim, circle.yml, config/locales/champaign.en.yml, spec/models/form_element_spec.rb, spec/requests/form_elements_spec.rb
This PR is to take care of two outstanding issues with surveys
I still need to write some specs for the changes in logic, but the dropdowns are working nicely in my click testing.
=> Add dropdown element to surveys

app/services/form_validator.rb, spec/services/form_validator_spec.rb
We're still getting an occasional invalid email error from AK. Just adding one more check to see if there's a dot right after @.
=> Check for period immediately after @

app/controllers/reset_passwords_controller.rb, app/mailers/reset_password_mailer.rb, config/locales/member_facing.de.yml, config/locales/member_facing.fr.yml, spec/controllers/reset_passwords_controller_spec.rb
`ResetPassword` has no associated page so must get its locale from the url.
=> Set locale from URI for reset password

config/locales/member_facing.en.yml, spec/controllers/reset_passwords_controller_spec.rb
=> Copy tweaks for password reset

app/services/form_validator.rb, spec/services/form_validator_spec.rb
https://sumofus.airbrake.io/projects/132583/groups/1809488884797438532
=> Another negative lookahead - starts with a dot

app/services/manage_action.rb, lib/payment_processor.rb, lib/payment_processor/braintree/one_click_from_uri.rb, spec/lib/payment_processor_spec.rb
+ allow multiple actions when donation
+ ignore case of currency
=> Fixes to oneclick

app/assets/stylesheets/member-facing/fundraiser.scss
=> Fixed paypal styling on freestanding fundraiser widget

app/assets/javascripts/member-facing.js.erb, package.json
=> Send JS errors on the member side to AirBrake

config/locales/member_facing.de.yml
For review and merge. French to come.
=> New DE copy

app/controllers/application_controller.rb, config/initializers/active_admin.rb, config/settings/development.yml, config/settings/production.yml, spec/controllers/application_controller_spec.rb
=> Raises when non-admin attempts to access the admin area.

lib/payment_processor/braintree/one_click_from_uri.rb, spec/features/express_donations/email_one_click_spec.rb
This checks that a customer exists when fetching a payment method id
=> Fix to one click

lib/payment_processor/braintree/webhook_handler.rb, spec/requests/api/braintree/webhook_spec.rb
https://sumofus.airbrake.io/projects/132582/groups/1826894570133023335?tab=overview
Ignore any webhook posts for subscriptions we don't manage.
=> Ignore webhook if subscription is missing

app/frontend/components/AmountSelection/AmountSelection.js, app/frontend/components/DonationBands/DonationBands.css, app/frontend/components/DonationBands/DonationBands.js, app/frontend/containers/FundraiserView/FundraiserView.js
=> Add option to highlight amount on FundraiserView

app/assets/stylesheets/member-facing/form.scss, app/liquid/views/partials/_form.liquid
Very small fix for the way that sweet placeholders are handled for textareas.
=> text-wrap the placeholder for multi-line text inputs

config/locales/member_facing.de.yml, config/locales/member_facing.en.yml, config/locales/member_facing.fr.yml
A bunch of translations removed as well, as I think they are now in SOU assets and these hadn't been updated in a while.
=> New translations

app/views/layouts/member_facing.slim, app/views/shared/_facebook_pixel.slim, config/settings/development.yml, config/settings/production.yml, config/settings/test.yml
need to set FACEBOOK_PIXEL_ID - get it here: https://www.pivotaltracker.com/story/show/135521493
=> Adds facebook pixel js snippet

app/liquid/views/partials/_survey_form.liquid, app/views/plugins/surveys/_survey.liquid, config/locales/member_facing.de.yml, config/locales/member_facing.en.yml, config/locales/member_facing.fr.yml
@edubsky Can you please add the missing translations? Thanks!
=> Added missing survey translations

.dockerignore, app/frontend/components/Payment/Payment.css, app/frontend/components/Payment/Payment.js, app/frontend/components/Stepper/Stepper.scss, app/views/plugins/fundraisers/_fundraiser_refactor.liquid, circle.yml, config/locales/member_facing.de.yml, config/locales/member_facing.en.yml, config/locales/member_facing.fr.yml
Fixes for all the little visual bugs that I turned up while QAing.
=> React fundraiser tweaks

app/controllers/twilio/calls_controller.rb, app/liquid/liquid_renderer.rb, app/models/plugins/call_tool.rb, app/services/call_creator.rb, app/services/twiml_generator.rb, config/application.rb, config/environments/development.rb, config/routes.rb, db/migrate/20170112103852_add_log_to_call.rb, db/schema.rb, spec/requests/twilio/calls_spec.rb, spec/services/twiml_generator_spec.rb
The call status is now logged after a call has ended.
=> Adds call status callback logging

config/routes.rb, spec/routing/api/actions_routing_spec.rb
Browsers without js enabled make a GET request to .../actions which raises. 
https://sumofus.airbrake.io/projects/132582/groups/1809054049423485339?tab=overview
=> restrict available action

app/frontend/ComponentWrapper.js, app/frontend/components/AmountSelection/AmountSelection.js, app/frontend/components/DonationBands/DonationBands.js, app/frontend/containers/FundraiserView/FundraiserView.test.js, package.json, yarn.lock
This has a few one-line fixes and finishes a couple tests
- the interaction was totally broken in IE 11 since we were missing a polyfill. I've added it.
- I've removed NZ / CA /AU from the amount buttons by just formatting those as USD on the buttons
- I've fixed a case where the Proceed button on Step 1 could get cut off and it wouldn't scroll.
=> More react fixes

app/frontend/components/Checkbox/Checkbox.js, app/frontend/components/Checkbox/Checkbox.test.js
=> Frontend tests

app/frontend/components.js, app/frontend/components/CallTool/Form.js, app/frontend/components/FieldShape/FieldShape.js, app/frontend/components/SweetInput/SweetInput.js, app/frontend/containers/CallToolView/CallToolView.js, app/models/plugins/call_tool.rb, app/services/call_creator.rb, app/views/plugins/call_tools/_call_tool.liquid, circle.yml, config/locales/member_facing.en.yml, spec/models/plugins/call_tool_spec.rb, spec/requests/twilio/calls_spec.rb
Also review this one please: https://github.com/SumOfUs/sou-assets/pull/20
=> Call tool updates

config/locales/member_facing.de.yml, config/locales/member_facing.fr.yml
Another PR coming on sou-assets as well.
=> Updated DE and FR translations

app/frontend/state/fundraiser/reducer.js
The form was always posting formId: 0 and we were getting a 404.
=> Fix 404 error when validating form from react fundraiser sidebar

app/assets/stylesheets/member-facing/form.scss, app/frontend/components/Braintree/BraintreeCardFields.js, app/frontend/components/Button/Button.scss, app/frontend/components/Checkbox/Checkbox.scss, app/frontend/components/ExpressDonation/ExpressDonation.scss, app/frontend/components/SweetInput/SweetInput.js, circle.yml
Our test with the refactor went badly, and based on the data, I think that our iPhone CSS was likely the culprit. This fixes a host of little things I found messing with it on iPhone, and I think enables us to do a new round of testing.
=> iPhone polish

app/assets/javascripts/member-facing/backbone/action_form.js, app/assets/javascripts/member-facing/backbone/survey.js, app/controllers/api/survey_responses_controller.rb, app/frontend/components/MemberDetailsForm/MemberDetailsForm.js, app/liquid/liquid_renderer.rb, app/views/plugins/fundraisers/_fundraiser.liquid, app/views/plugins/petitions/_petition.liquid, app/views/plugins/surveys/_survey.liquid, spec/liquid/liquid_renderer_spec.rb
This will allow us to attribute shares from spreader emails/
=> pass referring_akid url parameter through to AK

.rubocop.yml, app/frontend/components/DonationBands/DonationBands.css, app/frontend/components/DonationBands/DonationBands.js, app/frontend/components/DonationBands/DonationBands.test.js, app/frontend/state/fundraiser/reducer.js, app/views/plugins/fundraisers/_form.slim, app/views/plugins/fundraisers/_fundraiser_refactor.liquid, config/locales/champaign.en.yml, db/migrate/20170213183955_add_preselect_amount_to_plugins_fundraisers.rb, db/schema.rb, spec/models/plugins/fundraiser_spec.rb
This adds a feature (off by default) that preselects a middle value in the list of donations. 
Adds a checkbox in the page edit view that allows you to set the default value for the page.
Also adds support for overriding with the `?preselect=1` or `?preselect=0` url parameters.
=> Preselect amount

app/frontend/components/CallTool/Form.js, app/frontend/containers/CallToolView/CallToolView.js, app/models/call_tool/target.rb, app/models/plugins/call_tool.rb, app/views/plugins/call_tools/_form.slim, app/views/plugins/call_tools/_target_form.slim, config/locales/champaign.en.yml, db/migrate/20170220145423_add_countries_flag_to_call_tools.rb, db/schema.rb, spec/factories/plugins_call_tools.rb, spec/models/plugins/call_tool_spec.rb
=> Call tool optional country targeting

Guardfile, app/controllers/twilio/calls_controller.rb, app/helpers/pages_helper.rb, app/services/call_creator.rb, config/routes.rb, db/migrate/20170206171650_add_member_call_events_to_calls.rb, db/schema.rb, spec/requests/twilio/calls_spec.rb
* Store Twilio events about ongoing calls
* Small fix for edit page sidebar
=> Call tool events

app/frontend/ComponentWrapper.js, app/frontend/components/Payment/Payment.js, package.json, yarn.lock
* npm packages updated (patch versions). `braintree-web` broke compatibility with previous patch version.
* Simplified ComponentWrapper
=> Minor updates

app/views/campaigns/edit.slim, config/locales/champaign.en.yml
Angus requested this feature, which is long overdue.
=> Show a list of pages on campaign edit page

app/assets/javascripts/campaigner-facing/shares_editor.js, app/helpers/pages_helper.rb, app/views/share/_copy_button.html.slim, app/views/share/emails/_email.html.slim, app/views/share/emails/_summary_row.slim, app/views/share/facebooks/_facebook.html.slim, app/views/share/facebooks/_summary_row.slim, app/views/share/twitters/_summary_row.slim, app/views/share/twitters/_twitter.html.slim, package.json, spec/helpers/pages_helper_spec.rb, spec/views/smoke_tests_spec.rb
This makes it easy for campaigners to share an sp share URL.
=> Button to copy ShareProgress URL to clipboard.

config/initializers/aws_sdk.rb, config/settings/development.yml, config/settings/production.yml, config/settings/test.yml
We should attach necessary permissions to default eb ec2 role.
=> Use default service role permissions instead

config/routes.rb, config/settings/production.yml
This reverts commit db395348de1b570ff2356f2ebb1aaff5594700e7.
=> Revert "Added media route"

.ebextensions/02_container_commands.config, circle.yml, config/environments/production.rb, config/settings/development.yml, config/settings/production.yml, config/settings/test.yml, lib/analytics.rb, lib/tasks/champaign.rake
Going to create a dedicated cache cluster for champaign
=> Separates caching service from currenty redis cluster

config/settings/production.yml, config/settings/test.yml
ENV var already added to Staging and Production
=> Move SumOfUs specific settings to env vars

app/javascript/components/ComponentWrapper.js, app/javascript/components/ComponentWrapper.test.js, app/javascript/components/DonationBands/DonationBands.test.js, app/javascript/components/DonationBands/__snapshots__/DonationBands.test.js.snap, app/javascript/components/Payment/Payment.js, app/javascript/components/__snapshots__/ComponentWrapper.test.js.snap, app/javascript/fundraiser/FundraiserView.js, app/javascript/packs/fundraiser_plugin.js, app/javascript/types.js, package.json, yarn.lock
Usage: Create a global `optimizelyHook` function: 
```js
window.optimizelyHook = function optimizelyHook() {
// This code will run when the component is mounted, and when it's updated
console.log('Optimizely hook!');
$('<p>Test</p>').insertBefore('.DonationButton');
}
```
Related: https://www.pivotaltracker.com/story/show/147913893
=> Add optimizely hook

app/services/call_creator.rb, spec/services/call_creator_spec.rb
https://www.pivotaltracker.com/story/show/149657267
=> CallTool: create action before making req to Twilio

app/javascript/call_tool/CallToolView.js, app/javascript/components/CallTool/Form.js
To avoid having `+1 +44 7889 912777` sent as the member's phone number.
=> Remove memberCountryCode from the call tool forms

config/locales/member_facing.fr.yml
This fixes French mistakes/typos and catches up `member_facing.en.yml` with missing translations.
Sorry for the gross diff: I had to yaml-lint the file coz Webpack was unable to build (and I couldn’t figure out why).
There’re a few `FIXME` to check out, but it’s ready for a French guy to carefully review the translations.
=> Fix member facing French locale

config/locales/champaign.en.yml
Pretty straightforward - keep the tips up to date with the functionality.
=> Update call tool-tips

app/javascript/campaigner_facing/form_element_creator.js, app/javascript/campaigner_facing/list_editor.js, app/javascript/packs/campaigner_facing.js, app/models/plugins/email_pension.rb, app/models/plugins/email_tool.rb, app/views/forms/_add_element.slim, app/views/plugins/email_pensions/_form.slim, app/views/plugins/email_tools/_form.slim, db/migrate/20170802215732_convert_email_subjects_to_array.rb, db/migrate/20170802231650_rename_email_subject_to_email_subjects.rb, db/schema.rb
This code can be DRYed up a bit, but I decided to wait til later in this sprint to see how much the forms for the two email tools diverge.
=> Allow multiple email subjects

app/controllers/plugins/email_tools_controller.rb, app/models/call_tool/target.rb, app/models/concerns/has_targets.rb, app/models/email_tool/target.rb, app/services/email_tool/plugin_updater.rb, app/views/plugins/call_tools/_dynamic_targetting.slim, app/views/plugins/email_tools/_form.slim, app/views/plugins/email_tools/_target_form.slim, app/views/plugins/email_tools/_targets.slim, config/locales/champaign.en.yml, config/routes.rb, spec/models/plugins/call_tool_spec.rb
Refactored how targets fields and keys are handled.
* TODO: write request spec for the endpoint used when uploading a csv
* TODO: Refactor Target models and HasTargets module.
=> Email Tool - Add ability to upload targets csv

app/admin/member.rb, db/migrate/20170811124034_add_compound_index_to_members.rb, db/schema.rb
=> Restrict filters to email_equals only. 

app/javascript/components/Braintree/PayPal.js, app/javascript/components/Payment/Payment.js, flow-typed/npm/braintree-web_v3.x.x.js
Add missing required fields: amount and currency
=> Fix PayPal checkout flow

Gemfile.lock, circle.yml
https://testing.sumofus.org 
Uses same DB as staging.
=> Adds testing env to circle config

config/routes.rb
https://sumofus.airbrake.io/projects/132582/groups/1983015229379733157?tab=overview
=> Removing unnecessary routes for member authentications

app/controllers/pages_controller.rb, spec/controllers/pages_controller_spec.rb
Trying to avoid getting this errors: https://sumofus.airbrake.io/projects/132582/groups/1982986568207328883/notices/2047201720473696741?tab=notice-detail
=> Removed respod_to from pages#show

app/services/call_creator.rb
https://sumofus.airbrake.io/projects/132582/groups/1989339313784907500?tab=notice-detail
=> Avoid race condition when creating call

app/javascript/components/ErrorMessages.js, app/javascript/components/SweetSelect/SweetSelect.js, app/javascript/email_pension/EmailPensionView.js, app/javascript/email_pension/SelectPensionFund.js, app/javascript/email_pension/SuggestFund.js, app/javascript/email_tool/EmailToolView.js, app/javascript/state/email_pension/actions.js
It's almost a rewrite but I've basically broken it down to a few separate components.
=> Fix Email Pension tool

Gemfile.lock, config/database.yml, docker-compose.yml
These are a couple changes I needed to make to get my local development environment to work right now. The docker-compose file has been changed to run host instead of the web container, and database.yml looks for host on the environment and falls back to localhost. I did also update bootsnap and the bundler version is newer.
=> PR with tiny changes that I needed for local environment

app/helpers/pages_helper.rb, app/views/pages/_settings_form.slim, config/locales/champaign.en.yml, config/settings/production.yml, config/settings/test.yml, spec/helpers/pages_helper_spec.rb
This was requested by the XMem team
=> Replace AK page links with links to AK Reports

package.json, yarn.lock
=> Update react-select dependency

app/javascript/components/SelectCountry/SelectCountry.js, app/javascript/components/SweetSelect/SweetHTMLSelect.css, app/javascript/components/SweetSelect/SweetHTMLSelect.js
trigger onChange only if it has been passed, and use the element value.
=> Fix onChange for SweetHTMLSelect

app/javascript/components/CurrencyAmount.js, app/javascript/components/DonationBands/DonationBandButton.js, app/javascript/components/DonationBands/__snapshots__/DonationBands.test.js.snap, app/javascript/fundraiser/FundraiserView.test.js
Avoid using AU$, NZ$, CA$, or even US$ (when in a non en-US locale). See [screencast](https://cloudup.com/iSUtkesBrza)
=> Use $ symbol for all localised dollar currencies

app/views/layouts/member_facing.slim, app/views/shared/_amplitude_snippet.slim, config/settings/development.yml, config/settings/production.yml
https://www.pivotaltracker.com/story/show/154837032
=> Adds amplitude sdk snippet

app/assets/stylesheets/member-facing/ios-hack.scss, app/assets/stylesheets/member-facing/petition.scss, app/javascript/member-facing/backbone/overlay_toggle.js
=> iOS overlay bugfix

README.md
Update test command in README.md #1106
=> update the test command for README

app/javascript/components/EmailEditor/EmailEditor.js
Fixes bug where target's name isn't being inserted into the body of the email.
=> Call update (if necessary) when props change

app/models/member.rb, spec/models/member_spec.rb
necessary for GDPR experiements
=> Adds 'consented' to personalization object

app/views/layouts/mobile_preview.html.slim
=> Show campaigner overlay on mobile preview

app/controllers/api/pending_action_notifications_controller.rb, config/routes.rb, db/migrate/20180525151104_add_fields_to_pending_action.rb, db/schema.rb, spec/requests/api/pending_action_notifications_spec.rb
exposes endpoints for updating pending action with email events (delivered, opened, bounced, clicked, etc)
=> email notifications api

app/views/layouts/member_facing.slim
This may fix some Int.Collator issues that we've been experiencing.
=> Move polyfill.io script to `head`. Polyfill unknown UAs.

app/javascript/packs/generic.js, app/views/layouts/generic.slim
Add access to  object from generic layout
=> Add generic pack

Gemfile.lock, bin/webpack, bin/webpack-dev-server, package.json, yarn.lock
The upgrade was pretty straight forward. I tested a couple of flows and everything seems to be working as expected.
=> Upgraded to Webpacker 3.5

app/assets/stylesheets/campaigner-facing/page-edit.scss, app/javascript/campaigner_facing/shares_editor.js, app/views/share/_new_form.slim, config/locales/champaign.en.yml
Displaying errors on the UI on the share forms. Works for all kinds of shares.
=> Display share form errors

app/controllers/pages_controller.rb, app/liquid/liquid_renderer.rb
fixes broken double opt in template
=> Allow custom rendering without cache

app/javascript/consent/ExistingMemberConsent.css
=> Change width unit to % when <= 700px

app/javascript/packs/fundraiser.js
See https://github.com/sindresorhus/query-string#arrayformat
=> Specify arrayFormat when parsing query strings in frontend

app/javascript/member-facing/track_shares.js, app/javascript/util/log_event.js
There were a few additional events around fundraising that I was hoping to add to Champaign. I also updated the social tracking, which was currently only logging shares on Facebook. In the logEvent I added a check for eventData, as empty events were firing into GA.
@osahyoun @Tuuleh Would you please be able to help review? Hopefully I didn't mess anything up.
Thanks!
=> GA events updates

app/javascript/member-facing/backbone/action_form.js, app/javascript/state/fundraiser/actions.js, app/javascript/state/fundraiser/reducer.js, app/javascript/state/fundraiser/types.js
See commit message body for the reasoning behind the changes.
=> Fix action form's .onSuccess behaviour

app/services/member_exporter.rb, spec/requests/api/member_services/subject_access_request_spec.rb
(cherry picked from commit a899f8d9954d704f587ce4ca4ac0cabac0ac93ef)
=> Add a check for page present before calling for its slug

app/views/layouts/generic.slim, app/views/layouts/member_facing.slim, config/locales/member_facing.fr.yml
* Update french translation for "Credit card"
* Move optimizely script to the bottom of `<head>` so that we can access `window.champaign.personalization` from optimizely experiments.
=> Release 2018-10-29

config/locales/member_facing.de.yml
=> Update German translation for subject

app/javascript/email_pension/EmailRepresentativeView.js
Simply adds the country selector to the email rep view.
=> Make country a required field

config/locales/member_facing.es.yml
Mainly member facing text (merge https://github.com/SumOfUs/sou-assets/pull/77 first). This is a first pass so the final copy will be updated once we get the complete translations.
=> Spanish translations (first pass)

config/locales/member_facing.es.yml
Ticket:
https://www.pivotaltracker.com/n/projects/2160586/stories/165217956
=> Replaced English Text with Spanish text for Member facing page

app/services/page_cloner.rb, spec/services/page_cloner_spec.rb
Ticket:
https://www.pivotaltracker.com/n/projects/2160586/stories/164566701
=> Fix: Error in cloning page having formless plugin

app/assets/stylesheets/member-facing/form.scss
- Radio button has been aligned to the same line
Linked ticket - https://www.pivotaltracker.com/n/projects/2160586/stories/165339392
=> UI changes:

Gemfile, Gemfile.lock, app/controllers/pages_controller.rb, app/helpers/pages_helper.rb, app/views/pages/feeds.rss.builder, spec/requests/pages_spec.rb
Ticket:
https://app.asana.com/0/1119304937718815/1122607826376315
=> Limit feeds by latest 10 records and truncate description

spec/fixtures/pension_funds/au.json
Ticket:
https://app.asana.com/0/1119304937718815/1123026212594268/f
=> Updated email address for BT financial group (Australia)

app/assets/stylesheets/member-facing/petition.scss, app/javascript/consent/ConsentControls.css, app/javascript/email_pension/EmailPensionView.scss
- Radio button and Submit button focussed while on TAB button interaction
=> Field Focus

app/views/plugins/fundraisers/_fundraiser.liquid
Added the code to track the error events in mixpanel
=> add mixpanel event to error events code

app/controllers/api/pages_controller.rb, app/javascript/campaigner_facing/page_edit_bar.js, app/services/page_updater.rb, app/views/pages/edit.slim, spec/controllers/api/pages_controller_spec.rb
Ticket:
https://app.asana.com/0/1119304937718815/1119306255619779
=> Show visible warning when AK resource is not selected

app/javascript/components/Payment/Payment.js
Trigger custom mixpanel event when member selects to store payment info in vault.
https://app.asana.com/0/1119304937718815/1129345339401597/f
=> Trigger mixpanel event

app/views/cdn/_dropzone.slim, app/views/layouts/application.html.slim, app/views/layouts/member_facing.slim
unpkg was very slow for me (and on staging, also) - massive latency
=> Move over to cdnjs

app/services/share_variant_builder.rb
Ticket:
https://app.asana.com/0/1119304937718815/1122570805890067
This PR depends on other PR
https://github.com/SumOfUs/share_progress/pull/21
Post that need to create a new version and update the version in Champaign Gemfile
=> Fix Share Progress params nil issue

app/controllers/api/payment/braintree_controller.rb, app/controllers/concerns/exception_handler.rb, app/views/layouts/member_facing.slim
* Use the ExceptionHandler concern to handle Braintree validation errors and return a `400 Bad Request` response
* Use strong parameters to validate transaction requests.
* Fix selectize issue by adding microplugin.
=> Improve transaction error handling

app/controllers/application_controller.rb, app/controllers/clone_pages_controller.rb
Suspecting and changing the sequence of protect_from_forgery method sequence and reintroduced in clone_pages controller
=> Fix: Invalid Authentication token error

app/models/pending_action.rb, app/services/pending_action_service/reminders.rb
Find members and actions in single lookup
=> Restrict lookup range to 20 days

app/controllers/plugins/call_tools_controller.rb, app/models/plugins/call_tool.rb, app/views/plugins/call_tools/_target_form.slim, config/routes.rb, spec/controllers/plugins/call_tools_controller_spec.rb, spec/models/plugins/call_tool_spec.rb
Ticket:
https://app.asana.com/0/1119304937718815/1119306812531877/f
=> Added CallTool Target Export

app/controllers/api/go_cardless_controller.rb, app/controllers/api/payment/braintree_controller.rb, app/javascript/components/Payment/Payment.js, app/liquid/liquid_renderer.rb, app/models/page.rb, app/services/manage_braintree_donation.rb, app/services/manage_donation.rb, spec/models/page_spec.rb
Ticket:
https://app.asana.com/0/1119304937718815/1126638674466817
=> Pass source param

app/javascript/components/Payment/Payment.js, config/locales/member_facing.de.yml, spec/models/plugins/plugins_spec.rb
Ticket:
https://github.com/SumOfUs/sou-assets/pull/96
Dependent PR:
https://github.com/SumOfUs/sou-assets/pull/96
=> By default check 'Monatlich spenden' checkbox for German lang pages

app/javascript/components/Payment/Payment.js
Ticket:
https://app.asana.com/0/1119304937718815/1145902137583345
=> Fix: Preselect Direct Debit or Paypal for existing members

app/javascript/util/directDebitDecider.js, app/javascript/util/directDebitDecider.test.js, app/lib/payment_processor/go_cardless/populator.rb, spec/lib/payment_processor/go_cardless/transaction_and_subscription_examples.rb
Ticket:
https://app.asana.com/0/1119304937718815/1146016602765177
=> Fix: Removed our account Gocardless unsupported currencies

app/javascript/components/Payment/Payment.js
Ticket:
https://app.asana.com/0/1119304937718815/1146226698023697/f
=> Fix: select DD for German page when user follow donate button from email

app/views/pages/_settings_form.slim
Ticket:
https://app.asana.com/0/1119304937718815/1128534357067621
=> Add --None-- to empty value

Gemfile.lock, app/controllers/member_authentications_controller.rb, app/helpers/pages_helper.rb, app/views/layouts/generic.slim, config/locales/member_facing.de.yml, package.json, yarn.lock
Last release before the rebranding work is published.
=> Release 2019-11-01

app/javascript/components/Payment/Payment.js, app/javascript/state/fundraiser/reducer.js
Ticket:
https://app.asana.com/0/1119304937718815/1150510329259209
=> Fix: Unable to select direct debit

app/helpers/config_helper.rb, config/settings/production.yml, config/settings/test.yml
=> Enable toggling on or off sending EOY donations data to the window

app/controllers/api/actions_controller.rb, app/controllers/api/emails_controller.rb, app/controllers/application_controller.rb, app/controllers/payment_controller.rb, app/javascript/components/Payment/Payment.js, app/javascript/legacy/member-facing/backbone/petition.js, app/javascript/legacy/member-facing/backbone/petition_and_scroll_to_consent.js, app/javascript/modules/api/index.ts, app/javascript/plugins/fundraiser/FundraiserView.js, app/javascript/plugins/petition/index.tsx, app/javascript/util/ChampaignClient/MailerClient.js, app/lib/facebook_pixel.rb, app/lib/payment_processor/braintree/subscription.rb, app/models/action.rb, app/views/api/emails/create_pension_email.js.erb, app/views/plugins/fundraisers/_fundraiser.liquid, spec/controllers/api/actions_controller_spec.rb, spec/controllers/api/go_cardless_controller_spec.rb, spec/controllers/api/payment/braintree_controller_spec.rb, spec/lib/facebook_pixel_spec.rb, spec/requests/api/braintree/braintree_spec.rb, spec/requests/api/emails_spec.rb
Ticket:
https://app.asana.com/0/1119304937718815/board
=> Fix Facebook pixel events

app/models/page.rb, app/services/manage_braintree_donation.rb, app/services/manage_donation.rb
Ticket:
https://app.asana.com/0/1119304937718815/1151209766241317
=> Fix: source parameter for post action donation

app/helpers/api/pages_helper.rb
Reverts SumOfUs/Champaign#1589
The order was correct, sorry for the mistake
=> Revert "Changed the order of images in the srcset attrib"

app/views/shared/_facebook_pixel.slim
Ticket:
https://app.asana.com/0/1119304937718815/1153387000681005
=> Fix: Safari unsupported arrow functions

app/controllers/api/actions_controller.rb
Ticket:
https://app.asana.com/0/1119304937718815/1130397411091478
=> Update source from email

app/services/action_queue.rb, app/services/manage_action.rb, app/services/manage_survey_response.rb, spec/lib/payment_processor/braintree/webhook_handler_spec.rb, spec/requests/api/action_confirmation_spec.rb, spec/requests/api/actions_spec.rb, spec/requests/api/braintree/braintree_spec.rb, spec/requests/api/go_cardless/go_cardless_spec.rb, spec/services/manage_action_spec.rb
...will pass `nil` if akid isn't present.
=> Pass mailing_id with actions if an AKID is in the parameters

vendor/theme/stylesheets/components/photos.scss
Asana Bug: https://app.asana.com/0/1119304937718815/1169540267799569
=> Fix strapline overlay on head image by bottom 0

Gemfile.lock, app/controllers/api/payment/braintree_controller.rb
device data wasn't being passed to BT
=> Correctly pass device data to BT

app/javascript/components/DonateButton.js, app/javascript/components/ExpressDonation/ExpressDonation.js, app/javascript/components/Payment/Payment.js, app/javascript/components/Payment/__snapshots__/doubleButtonConditions.test.js.snap, app/javascript/components/Payment/doubleButtonConditions.test.js
Display one_off & recurring buttons in payments & express donation for fundraising & petition based on recurring_default URL param with respect to member role.
=> Override recurring_default param for fundraising & petition

app/javascript/plugins/email_tool/EmailToolView.js, spec/services/email_tool_sender_spec.rb
Tiny tiny fix for a bug that took me forever to uncover.
=> Fix custom action fields for email tool actions where there are multiple targets

config/environments/production.rb
Expose PROD api to peoplevsbigtech localhost to check petition iframe
=> peoplevsbigtech work

vendor/theme/translations/sumofus.nl.yml
Asana Ticket - https://app.asana.com/0/1119304937718815/1201364583110694/f
=> Update email lang for Dutch

vendor/theme/templates/layouts/post-donate-page-with-recurring-ask.liquid
* Adding Arabic to the post donate page with recurring ask liquid template.
* NOTE: We need translations and the real donate page link, but I will add that in a follow-up PR.
=> Arabic Post Donate Page With Recurring Ask 

app/assets/stylesheets/member-facing/form.scss, app/assets/stylesheets/member-facing/petition.scss, app/assets/stylesheets/member-facing/thermometer.scss, app/javascript/components/Braintree/Braintree.scss, app/javascript/components/Braintree/BraintreeCardFields.js, app/javascript/components/Stepper/Step.js, app/views/api/pages/show.json.jbuilder, app/views/layouts/member_facing.slim, config/locales/member_facing.ar.yml, spec/requests/api/pages_spec.rb, vendor/theme/stylesheets/components/logo.scss, vendor/theme/stylesheets/components/petition.scss, vendor/theme/stylesheets/components/photos.scss, vendor/theme/stylesheets/global/layout.scss, vendor/theme/templates/layouts/post-donate-page-with-recurring-ask.liquid, vendor/theme/templates/partials/_progress_tracker.liquid
Reverts SumOfUs/Champaign#1874
Issue with logo, reverting for now
=> Revert "Release"

app/assets/stylesheets/member-facing/form.scss, app/assets/stylesheets/member-facing/petition.scss, app/assets/stylesheets/member-facing/thermometer.scss, app/javascript/components/Braintree/Braintree.scss, app/javascript/components/Braintree/BraintreeCardFields.js, app/javascript/components/Stepper/Step.js, app/views/api/pages/show.json.jbuilder, app/views/layouts/member_facing.slim, config/locales/member_facing.ar.yml, spec/requests/api/pages_spec.rb, vendor/theme/stylesheets/components/logo.scss, vendor/theme/stylesheets/components/petition.scss, vendor/theme/stylesheets/components/photos.scss, vendor/theme/stylesheets/global/layout.scss, vendor/theme/templates/layouts/post-donate-page-with-recurring-ask.liquid, vendor/theme/templates/partials/_progress_tracker.liquid
Reverts SumOfUs/Champaign#1877 and includes the necessary RTL fixes
=> Revert "Revert "Release""

vendor/theme/templates/layouts/post-donate-page-with-recurring-ask.liquid
=> Arabic translations for post donate with recurring ask page

vendor/theme/templates/layouts/post-donate-page-with-recurring-ask.liquid
=> Fixed Comma on Arabic Version

app/javascript/components/Checkbox/Checkbox.scss, app/javascript/components/ExpressDonation/ExpressDonation.scss, app/javascript/components/Payment/Payment.css
The express donation is missing some RTL styles making the page look wrong in the Arabic version.
https://app.asana.com/0/1119304937718815/1201953319712623/f
**Before:**
**After:**
=> Added Missing RTL styles

app/views/api/pages/show.json.jbuilder
* The fundraiser title is dynamic, and we need to use that value on pronto. Right now the API is not returning it; therefore, we are always using "Donate now" as the title for all the languages on pronto.
https://app.asana.com/0/1119304937718815/1202023632315774/f
**Request:**
```console
curl --location --request GET 'http://localhost:3000/api/pages/test-petition-123.json'
```
**Response:**
```json
{
"id": 13,
"title": "test petition 123",
"slug": "test-petition-123",
"content": "",
"created_at": "2022-04-06T20:54:49.715Z",
"updated_at": "2022-04-06T22:39:27.108Z",
"publish_status": "unpublished",
"featured": false,
"action_count": 0,
"campaign_action_count": 0,
"meta_description": "",
"template_name": "Default: Petition And Scroll To Donate Greenpeace",
"follow_up_template": null, …
```
=> Adding the fundraiser title to the pages API

config/environments/production.rb
[A Partner wants to embed a Champaign page on their website!](https://app.asana.com/0/1119304937718815/1202079182461794/f)
- Page that they want to embed - https://actions.sumofus.org/a/os-povos-indigenas-precisam-de-voce-agora
-  We are exposing our API to get actions recorded from their domain
=> API access given to external org

config/settings/development.yml
I created a new optimize container for staging env so we can easily develop and test our AB experiments, this PR updates the container ID
=> Using staging container for dev environments

config/settings/production.yml
Updated the development settings on #1922, but staging deploy uses the production yml file.
I am adding an env variable or defaulting to the production container.
=> Env variable for optimize container or default to prod value

app/javascript/experiments/unintended-donations.js
While testing, I mistakenly pressed to recreate the staging experiment, which created a different id. I need to update the id to resume my testing
=> Updated experiment id

app/controllers/application_controller.rb
Patching the comparison logic and using the member_id cookie
=> Fixing ids comparison

app/controllers/application_controller.rb, app/javascript/experiments/unintended-donations.js, app/javascript/plugins/fundraiser/FundraiserView.js
Cleaning up the debugging code from #1921 before releasing it to production and also updating the experiment ID to use the production ID.
=> Unintended Donations Follow-up

app/controllers/api/payment/braintree_controller.rb
* Modified success to be bool instead of returning all the data
=> One click api endpoint - Follow up 

app/javascript/experiments/unintended-donations.js
We will run the [unintended donations experiment](https://optimize.google.com/optimize/home/#/accounts/4704836760/containers/15164063/experiments/27) on a different [fundraiser](https://actions.sumofus.org/a/help-save-the-vaquita) and for that, we need to update the ID on the codebase.
The previous version of the experiment ran on a [Nestle](https://actions.sumofus.org/a/let-s-buy-nestle-da81bd9a-0b83-4b3e-9143-8a0255ce2f26) fundraiser
https://app.asana.com/0/1202125528509940/1202125539219755/f
=> Update experimentId For 2nd Round of Experiments

app/lib/payment_processor/braintree/one_click_from_uri.rb
Reverts SumOfUs/Champaign#1947
=> Revert "Adding logs to troubleshoot one_click endpoint"

config/initializers/application_secrets.rb
=> Temp change to debug issue with deployment on staging

app/lib/secrets_manager.rb
=> Temp change to debug deployment issue (Hardcoded aws region)

.circleci/deploy.sh, app/lib/secrets_manager.rb
=> Temp change to debug issue with deployment

app/lib/secrets_manager.rb, config/application.rb, config/initializers/application_secrets.rb
* Added log on the rescue statement if the `secrets_manager` class for better troubleshooting on production.
* Added missing BT setting.
* From what I observed on the errors from the tests (the ones ran in this PR as debugging code) I think this might be the cause for the issues on sentry and paper trail with an error message like this: `["NoMethodError", "undefined method `attributes' for nil:NilClass"] `
https://app.asana.com/0/1119304937718815/1202511330233412/f
Given the urgency to fix the production experiment, I'll deploy this without reviews, but if @subbiahf22 @osahyoun  have feedback, I'll happily address it on a follow-up PR.
=> Debug code on secrets manager

app/views/layouts/member_facing.slim, app/views/shared/_ad_agency_pixel.slim, vendor/theme/templates/layouts/email-members-of-united-kingdom-parliament.liquid
Includes #1982 
* Adds tracking pixels for FB, Instagram & tiktok
* Updated condition check for specific campaign
=> Adds tracking pixels for FB, Instagram & tiktok for a specific campaign

app/javascript/experiments/unintended-donations.js
We will run the [unintended donations experiment](https://optimize.google.com/optimize/home/#/accounts/4704836760/containers/15164063/experiments/38) on a different [fundraiser](https://actions.sumofus.org/a/chip-in-to-sumofus-s-citizen-clean-up-fund) and for that, we need to update the ID on the codebase.
The previous version of the experiment ran on a [Vaquita](https://actions.sumofus.org/a/help-save-the-vaquita) fundraiser
https://app.asana.com/0/1202125528509940/1202125539219755/f
=> Update experimentId For 3rd Round of Experiments

vendor/theme/templates/partials/_social_share_band.liquid
Follow-up for #2018, during my production testing, I found a bug 🐛 when the page body does not match the selector for getting the first paragraph. I fixed the selector and added a guard if it didn't match. The button still works and fallback to an empty string.
=> Null guards and fixed selector

app/javascript/modules/EmailParliament/EmailComposer.js, app/javascript/plugins/email_pension/EmailPensionView.js, app/javascript/plugins/email_tool/EmailToolView.js, app/javascript/state/consent/index.js
- This involves Consent Ask view change in 3 different Emailing tools
1. Email Tool
2. Email Pension View
3. Email MP Tool
https://user-images.githubusercontent.com/105354588/188084169-462f0280-8a35-4599-bcf2-089a3c4c37bf.mp4
=> Email Tool: Email change enables consent ask view

app/controllers/api/pages_controller.rb, config/routes.rb
To add the functionality of updating the publish status of the page from the campaigner's popup on pronto
- Create a new route to access the API from pronto
- To remove the authenticity token since the update functionality is accessed by the pronto endpoint
- To add the token check condition to secure the endpoint 
**Request**
```curl 'http://local.sumofus.org:3001/api/page/update?id=8429' \
-X 'PUT' \
-H 'Accept: */*' \
-H 'Accept-Language: en-US,en;q=0.9,ta-IN;q=0.8,ta;q=0.7' \
-H 'Connection: keep-alive' \
-H 'Content-Type: text/plain;charset=UTF-8' \
-H 'Cookie: _session_id=SWFtL3dmQWR3MkNEU1V5QkVVclVBOTRtYVZ0ZElFNDhLR25KemRyVzA1VVVXSzVhSnhhd2tTck8wMzNJazlzc1EwOVZUK3ozYnFlbkEwL3lvbVErSWdDbXR5OWorS1E1UFVDaDI2VEJWMkRCT2lWbi9nbng4QnZ5bkgyZUIyR3dIdGVrSHNzQ2l2a3dlaUVXN3ZYUUNFQTZuOXRISHpSdWw …
```
=> Page Publish Update

.circleci/config.yml, .ebextensions/02_container_commands.config
@subbiahf22  @osahyoun this PR is to revert the direct changes we had to make due to the production incident.
=> Undo master changes

app/views/api/pages/show.json.jbuilder, spec/requests/api/pages_spec.rb
Task: https://app.asana.com/0/0/1202939091766853/f
- shares consists of text required by WhatsApp button
=> Embedding "shares controller"'s "title" in share_button for Whatsapp.  

app/controllers/api/payment/braintree_controller.rb
Reverts SumOfUs/Champaign#2042
=> Revert "Removing bot verification until pronto ReCaptcha is fixed"

app/views/pages/_follow_up_action_settings.slim, app/views/pages/edit.slim
Found an issue while testing #2043. I was checking for the template id, but the ids vary from environment to environment, and the new functionality wasn't working on staging.
I changed the checks to use the template title, which is the same across environments.
=> Monthly sustainers patch

app/assets/stylesheets/member-facing/campaigner-overlay.scss, app/views/pages/_campaigner_overlay.slim
Added Copy URL Option in Champaign Overlay. 
Ticket: https://app.asana.com/0/0/1203056138127531/f
Screenshot:
=> Added Copy URL in Campaign Overlay

app/javascript/components/ExpressDonation/ExpressDonation.js, app/javascript/components/Payment/Payment.js
-> This will make sure whenever the Monthly button is disabled, not to switch the button theme
=> Use showMonthlyButton as condition in Payment btn

vendor/theme/templates/layouts/petition-and-scroll-to-donate.liquid, vendor/theme/templates/partials/_donation_ask_with_thermometer.liquid, vendor/theme/translations/sumofus.de.yml, vendor/theme/translations/sumofus.en.yml, vendor/theme/translations/sumofus.es.yml, vendor/theme/translations/sumofus.fr.yml, vendor/theme/translations/sumofus.nl.yml, vendor/theme/translations/sumofus.pt.yml
* The year was hardcoded on the donate question for the scroll-to-donate template.
*  Using current year.
* Updated other templates using the same translation.
* For Arabic, there weren't changes as the year is not in the translation.
https://app.asana.com/0/1119304937718815/1203050335588363/f
=> Using current year for translations

vendor/theme/templates/layouts/Default:-petition-and-scroll-to-donate-greenpeace.liquid, vendor/theme/templates/layouts/Default:-petition-and-scroll-to-share-greenpeace.liquid, vendor/theme/templates/layouts/end-of-year-scroll-to-share-2020.liquid
Reverts SumOfUs/Champaign#2071
=> Revert "Adding new fb pixel event"

package.json, yarn.lock
Reverts SumOfUs/Champaign#1990
=> Revert "Bump moment from 2.26.0 to 2.29.4"

yarn.lock
Reverts SumOfUs/Champaign#2002
=> Revert "Bump terser from 4.7.0 to 4.8.1"
